### ISSUE TITLE
Implement blocking via `declarativeNetRequest` API

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1156]
Parent Issue: https://github.com/ipfs/ipfs-companion/issues/1152
~~Blocked By: https://github.com/ipfs/ipfs-companion/issues/1155~~

ETA: 2023-05-05

```[tasklist]
### Tasks
- [x] Implement `declarativeNetRequest` to update URL blocking based on populated LFU.
- [x] Route blocked requests conventionally.
```

**Comment by SgtPooki** [comment]
@BigLep this is the issue tracking the user-value benefits of ipfs-companion once mv3 is done

**Comment by BigLep** [comment]
@whizzzkid : what is meant by "Route blocked requests conventionally"?  Is that the end of the done criteria?
