### ISSUE TITLE
[MV3 Beta Bug] Automatic mode does not work automatically on Brave or Chrome

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1204]
Gateways only get invoked when the first-class "IPFS” button in the address bar is hit manually.

**Comment by BigLep** [comment]
@whizzzkid : my feedback on this was under the heading "Experience with fresh install on Brave without using Kubo (neither Brave-managed Kubo or external Kubo)"

I'm intentionally not using Kubo.

https://www.notion.so/pl-strflt/Dogfooding-4560b1a6cd7a494ca5ac5b1bc7d6cd4a?pvs=4#a39d3a036f494c9c8427efd739a1ce19

**Comment by BigLep** [comment]
@whizzzkid : when is Automatic mode supposed to work.  

From the settings menu it says "Automatically switch from your local gateway to your default public gateway if the Kubo RPC is unavailable."

If I don't have a Kubo node running (and thus not Kubo RPC endpoint and no local gateway) visiting sites like ipfs.tech don't redirect to my external gateway (e.g., ipfs.io).  I would expect when visiting ipfs.tech to be redirected to https://ipfs-tech.ipns.dweb.link/.

I can confirm this doesn't appear to work with "IPFS Companion RC-MV3 (Beta @ 9f4981c)" on both Chrome and Brave.

**Comment by BigLep** [comment]
Thanks @whizzzkid .  I was able to ask @lidel some more companion questions during a 1 on 1.

I'm still struggling with this option to make sure I understand what it does.

If I use companion, have "automatic mode" enabled, and visit http://docs.ipfs.tech.ipns.localhost:8080/, I don't get automatically redirected.  I get a redirect indirect I need to interact with (which make sense from a security regard) (see below).  That said, I see this interstitial regardless of whether I have "automatic mode" enabled or not.

I am wanting to make sure I understand what "Use Automatic Mode - Automatically switch from your local gateway to your default public gateway if the Kubo RPC is unavailable" means. When does this "automatic mode" get invoked?  What is the difference in behavior between enabling it vs. disabling it?

<img width="1180" alt="image" src="https://github.com/ipfs/ipfs-companion/assets/85411/47369887-93ef-4364-b779-046b94b0f773">

**Comment by lidel** [comment]
Some historic notes:
-  "Automatic Mode" was introduced to disable redirect to local gateway when it was down, and re-enable it when it gets back online.  
   - It was never applied to public gateways, as we did not want to centralize all requests to PL-controlled gateway (back then, we did not even have Cloudflare gateway, so any decentralization via community-run gateways we could get, was a win).
   - So there is no automatic redirect when local node is not present. Instead, for non-local HTTP, we use preferred gateway only for error recovery: if a request to public HTTP server fails, but Companion knows it is a public gateway URL or DNSLink website, we recover via local or public gateway URL (depending on  automatic mode state).
      >  ![2023-06-20_17-57](https://github.com/ipfs/ipfs-companion/assets/157609/a76ce7ad-9d8e-431f-9337-eaa60d62af7a)

> On a side note @lidel do you know of a different reason of why localhost requests that were failing did not redirect to public gatways when "automatic mode" was on?

Well, we've introduced a nice UX in https://github.com/ipfs/ipfs-companion/pull/1125 – when local node goes/is offline, and localhost page load fails, we don't magically redirect user to public gateway (which could leak their browser history, and suddenly have no integrity check, as its delegated to third party HTTP server).

- Instead, Companion [shows this nice recovery HTML page](https://user-images.githubusercontent.com/1895906/216529833-54450744-ed71-4151-a864-e3b4e0517682.png), which allows user to either retry (after starting local node) or open via public gateway (but this is explicit decision by user, prefaced with security/privacy warning).

------

So with that in mind, I would not change the behavior of "Automatic Mode" or Recovery Page when local node is not available. 

Perhaps all we need is to clarify "Automatic Mode" label, note that all it does is toggling redirect to LOCAL gateway.

> Use Automatic Mode - redirect to your local gateway only when Kubo RPC is available.

**Comment by BigLep** [comment]
Thanks @whizzzkid and @lidel for explaining the intent.  This makes sense to me now.  Hopefully I make the time up to you guys by being self-sufficient in future in helping others or improving/reviewing docs.

Anyways, I think updating the settings text to be more clear.   

> Use Automatic Mode - redirect to your local gateway only when Kubo RPC is available.  

Maybe also add extra text or help note:

> Disabling this still triggers redirects even if the Kubo RPC endpoint is unavailable.  

Basically I think we want to get the message across that "If your local gateway's availability is corroborated with the Kubo RPC endpoint availability, then you likely only want to redirect if your gateway and Kubo RPC are up."
