### ISSUE TITLE
Remove/Replace Embedded Node Type

### ISSUE THREAD

**Issue by whizzzkid** [ipfs-shipyard/ipfs-companion#1220]
Embedded node types will not be supported in Mv3, Helia in service-worker context can provide an alternative, however service-workers in chrome-extension mv3 has its own limitations: https://github.com/w3c/webextensions/issues/72 The biggest ones are the lack of webRTC streams and webSockets.

More work will be needed to explore this.

**Comment by BigLep** [comment]
I like the idea of replacing, but that's a bigger endeavor.  Do we instead just break this into two steps:
1. Remove embedded/js-ipfs
2. Add something better back in

Basically, if it's not a lot of work to remove, lets make our maintenance burden lighter by get rid of code that isn't tested and isn't supported anymore.

**Comment by BigLep** [comment]
@whizzzkid : I think we should remove it everywhere.  We're not able to support it in Firefox if users have issues.  I assume it also cleans up the code to to remove it everywhere.  Lets definitely remove it from docs and UI as well.  It's not clear at this point if/when we'll replace it with Helia, so I think better to be accurate to where we are.
