### ISSUE TITLE
[MV3 Beta Bug] Redirect infinite loop with Brave when hitting "purple IPFS button"

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ipfs-companion#1283]
**Describe the bug**
I can get Brave into a redirect loop

**To Reproduce**
1. Use external Kubo node (e.g., IPFS Desktop)
2. Clear all redirect rules.
3. Go to https://explore.ipld.io
4. Browser bar becomes http://explore.ipld.io.ipns.localhost:8080/
5. Hit purpose "IPFS" button in address bar
6. Browser redirects to https://explore-ipld-io.ipns.dweb.link/ but white screen
<img width="1428" alt="image" src="https://github.com/ipfs/ipfs-companion/assets/85411/0f42e6dd-a243-4544-89ba-79bc507e3d3a">
8. Refresh redirects to http://explore.ipld.io.ipns.localhost:8080/
9. After that I can't reproduce it.  It seems to be a first-time issue.  I have to clear redirect rules to trigger this again.

**Versions**
- Companion 3.0.0.1131
- Brave 1.57.47 Chromium: 116.0.5845.96 (Official Build) (arm64)

**Comment by lidel** [comment]
@BigLep what are your settings on `brave://settings/ipfs`, mainly resolution method? Gateway?

> ![2023-09-20_18-19](https://github.com/ipfs/ipfs-companion/assets/157609/3de66941-8fa0-441d-9dc4-6945e8091a90)
