### ISSUE TITLE
Add support for HTTP Gateway root

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#14]
When  https://github.com/jbenet/go-ipfs/issues/807  is implemented, this addon could provide an easy UI for going to the page  with one click (if custom gateway is enabled).

**Comment by lidel** [comment]
Quick update: as of today, button-panel (https://github.com/lidel/ipfs-firefox-addon/issues/32) provides an easy way to open WebUI provided by go-ipfs.  

Future resources will probably land in the same place.

**Comment by jessicaschilling** [comment]
@lidel OK to close this one?
