### ISSUE TITLE
Captain.log - ipfs-companion

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#265]
![](https://camo.githubusercontent.com/9b3028b4086f450a98ec68144d360994de13b4bf/687474703a2f2f77702e70726f64756374696f6e2e70617468656f732e636f6d2f626c6f67732f6578706c6f72696e676f75726d61747269782f66696c65732f323031342f30372f696d616765312e6a7067)

I feel it may be a good idea to maintain captain.log for this project.

Quoting [`ipfs/community` guidelines](https://github.com/ipfs/community/blob/master/captain.log.md), the log will be a short summary of what is going on,  our the current challenges and will provide some direction to newcomers and current contributors on where the project could use some extra hands.

**Comment by lidel** [comment]
I've merged `zh_CN` translation (#262), decided to ignore `package-lock.json` feature of NPM5 due to stability issues (#261), and started working (https://github.com/ipfs/ipfs-companion/commit/a10ce15950b3caf1b4e10fec5d728e8011f8f829) on serious refactoring in `browser-action-port` branch. 

The goal is to replace alarm-based updates with more robust and portable message-based signaling based on `browser.runtime.connect` API. When finished, it will fix multiple bugs and improve UX under Chromium-based browsers.

**Comment by lidel** [comment]
### Chrome 
We now support one-click install via [Chrome Web Store](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch): 

[![](https://developer.chrome.com/webstore/images/ChromeWebStore_BadgeWBorder_v2_206x58.png)](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch)

### Firefox

Publishing of WebExtension for Firefox is blocked by https://github.com/ipfs/ipfs-companion/issues/269. 
Until it is resolved one can [install it from Developer Channel](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta) instead.

**Comment by diasdavid** [comment]
@lidel would you like to give a demo on the next IPFS All Hands?

**Comment by lidel** [comment]
@diasdavid sure, email me the details (time, screen sharing software etc)

**Comment by lidel** [comment]
Long time no log!

- **Finished move to WebExtensions! (#20)**
  IPFS Companion v2.0.13, has been approved and is now available for download in Mozilla's gallery at https://addons.mozilla.org/addon/ipfs-companion/ 🎉 ✨ 
  Most of features from the legacy add-on will still work, only regression being the lack of custom protocol in Location Bar. Users should get automatic updates in the following days.
Big thanks to @dignifiedquire and @diasdavid  for work related to removal of `unsafe-eval` from extension's CSP (#269), and to everyone testing beta versions in past months!
- I gave a small demo around 9:30 mark of [Sep 4 2017 - IPFS all hands call 🙌🏽](https://youtu.be/chAXj_vsR2s?t=561) 
- We have no false-positives anymore. For `/ipfs/` paths, CID must be valid v0 or v1. For `/ipns/` peerid needs to be a valid multihash or a FQDN with dnslink in TXT record.
- Due to the lack of proper APIs (#164) custom protocols (`ipfs://`, `dweb:/ipfs/` etc) are normalized to HTTP gateway. This occurs when special URI/URL is pasted to Location Bar or present in `src` and `href` attribute of DOM element. This provides users with good UX  in both Firefox and Chrome.
- Had a lot of fruitful discussion during the Lab Week! 
  If anyone is interested in **the future of browser extension**, here are some notes on what's next:
  - _IPFS in Web Browsers & Future of Browser Extensions_ (session notes) 
    https://github.com/protocol/lab-week-unconf/issues/23
  - _Roadblocks for IPFS in Browser Extension_ (memo)
    https://github.com/ipfs/in-web-browsers/pull/60

**Comment by dignifiedquire** [comment]
Great to hear things worked out! 🎉

**Comment by lidel** [comment]
We grew too big for old school captain log :) 

For future updates, see:

- Companion: https://github.com/ipfs/ipfs-companion/releases
- Integration with Web Browsers: https://github.com/ipfs/in-web-browsers/tree/master/meeting-notes
- IPFS Weekly: https://github.com/ipfs/newsletter/
