### ISSUE TITLE
Display progress of Quick Upload

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#295]
There should be some form of visual feedback when user is uploading a big file.

Adding a progress indicator should be possible when changes listed in https://github.com/ipfs/js-ipfs-api/issues/608 are released 🤔

**Comment by cvan** [comment]
What ought to be the file-size recommendations/limits for file uploads?

**Comment by lidel** [comment]
This remains an open question. 

I suspect there will be different choke points depending on what IPFS node type is used:
- If extension is set up to use external IPFS node, then we have potential transfer speed limits introduced by `js-ipfs-api` (HTTP API Client library) and then storage characteristics of `go-ipfs` come to play. 
- If embedded `js-ipfs` is used, then we have limits imposed by browser vendor on memory use and max local storage size per extension. 

In addition to the above, if upload is performed via `window.ipfs` object, then there may be a small speed overhead introduced by [ipfs-postmsg-proxy](https://github.com/tableflip/ipfs-postmsg-proxy).

Expect these to be benchmarked at some point, but looking at https://benchmark-js.ipfs.io I am rather optimistic about every day use.

**Comment by lidel** [comment]
Progress indicator shipped with [v2.3.0](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.3.0).  Works best with embedded node.
There are remaining issues such as long buffering when external node is used, but these things will be addressed in upstream libraries.
