### ISSUE TITLE
Muon-based Brave Browser Integrations 

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-companion#312]
>  - Brave [switched to Chromium in 2018](https://web.archive.org/web/20181017002230/https://brave.com/development-plans-for-upcoming-release/) so I collapsed outdated notes that were related to Muon-based Brave build.  
> - IPFS Companion works perfectly with Chromium-based Brave, and this PR updates our docs to reflect that (https://github.com/ipfs-shipyard/ipfs-companion/pull/609)
> - We now work toward bundling go-ipfs with Brave, with the goal of having something similar to how [Tor Tabs](https://brave.com/tor-tabs-beta) work. 
> - **Follow** → https://github.com/brave/brave-browser/issues/819
>
> – @lidel, _Q4 2018_

---- 

<details>
  <summary>Click to expand historical notes about Muon-based Brave (early 2018)</summary>

`ipfs-companion` runs in brave! 

The following ipfs address styles resolve, either to a local gateway, or the public one.

- ipfs.io/ipfs/QmZyRCtk8MGpuWXn2d1QyTfLWKMTHrT2aHs2vDkfry5zKT
- ipfs://QmZyRCtk8MGpuWXn2d1QyTfLWKMTHrT2aHs2vDkfry5zKT
- dweb:/ipfs/QmZyRCtk8MGpuWXn2d1QyTfLWKMTHrT2aHs2vDkfry5zKT

![screenshot 2017-11-16 10 14 43](https://user-images.githubusercontent.com/58871/32887068-9596dfd0-caba-11e7-954c-494ef255e52f.png)

In the case of `ipfs://` style, brave prompts the user if it's ok to "open in an external application. The url shown is the gateway url rather than what's been entered in the url bar, which could cause confusion. 

![screenshot 2017-11-16 10 15 03](https://user-images.githubusercontent.com/58871/32887083-9eaf5926-caba-11e7-9490-2ea026727c41.png)

A nice feature of using the `ipfs://` form is that it is preserved in the url bar. The other forms are translated to a gateway url.

NURI style isn't supported (just for completeness)
/ipfs/QmZyRCtk8MGpuWXn2d1QyTfLWKMTHrT2aHs2vDkfry5zKT is redirected to
file:///ipfs/QmZyRCtk8MGpuWXn2d1QyTfLWKMTHrT2aHs2vDkfry5zKT

Brave supports a subset of the the chrome-extensions api, so there are few issues to figure out.

## Things to get working

- ☑️  **Open Preferences** menu item fails silently. Nothing happens on click. 
- ☑️ Browser action icon. Silently fails to render... I've tried both the svg and explicitly overriding it to the png (possibly caused by https://github.com/brave/browser-laptop/issues/11797 ,  https://github.com/brave/browser-laptop/pull/11143)

### Missing apis

We can talk to brave about getting this enabled in muon.

- ☐ `contextMenus.create` (_means no ipfs option appears when right clicking on a page_)
- ☐ `contextMenus.update`
- ☐ `idle.queryState`
- ☐ `runtime.openOptionsPage` (_this causes the **Open Preferences** fail_)

_Requested, https://github.com/brave/browser-laptop/issues/9556#issuecomment-345229249_

### Minor

- ☐ **Copy canonical address** and **Copy public gateway url** works, but there is a console error afterwards
```
Uncaught (in promise) {message: "Access to extension API denied."}
```
- ☐ Same issue with pin and unpin
- ☐ open webui works, but brave blocks a resource used by the webgl **connections** globe. (help requested: https://github.com/brave/browser-laptop/issues/9556#issuecomment-347207918 ) Proposed solution: https://github.com/brave/browser-laptop/issues/9556#issuecomment-347612006
```
WebGL: http://127.0.0.1:5001/ipfs/QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ/#/connections
```
- ☑️ The action menu drop down resizes several times during rendering, which is quite slow in brave and looks awkward. Related to #318 

</details>

**Comment by olizilla** [comment]
### Open Preferences menu item fails silently. Nothing happens on click.

`browser.runtime.openOptionsPage()` throws with an error `Access to extension API denied.` if run from browser-action.js directly, as in the current impl. I tried moving the call back `ipfs-companion.js` and calling it remotely via the api `postMessage` which resulted in a different error: "Could not create an options page."`

**Comment by olizilla** [comment]
ipfs address flavours tester page https://ipfs.io/ipfs/QmP2yCrvuL89kgCxtt5vXfPMt89PtidxQ8yKTr86gtYZd4

**Comment by olizilla** [comment]
### Registering Protocol Handlers

Brave / muon makes `chrome.protocol.registerStringProtocol` available to trusted extensions. This is great as it allows us to return content directly from an embedded js-ipfs node, rather than redirecting to a local node. As it allows us to respond with strings this means we are limited to text/* and svg files; no images / videos and other byte array like things.

Here is the current definition of the protocol object available
https://github.com/brave/muon/blob/master/atom/common/api/resources/protocol_bindings.js

If we can update that to include

- [ ] [`protocol.registerBufferProtocol`](https://github.com/brave/muon/blob/master/docs/api/protocol.md#protocolregisterbufferprotocolscheme-handler-completion)
- [ ] [`protocol.registerStreamProtocol`](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterstreamprotocolscheme-handler-completion) 

then we can (I assume) start handling requests for images / videos and dealing with large files.

It looks like the muon code base already supports `registerBufferProtocol`, and this is the biggest blocker to a good ipfs experience right now.

`registerStreamProtocol` only exists in electron at the moment, so it will be more work to port it over to muon, but at least there is prior art to work from.

https://github.com/brave/muon/blob/master/docs/api/protocol.md
https://github.com/electron/electron/blob/master/docs/api/protocol.md

**Comment by olizilla** [comment]
PR to port `registerStreamProtocol` to muon is go! https://github.com/brave/muon/pull/507

**Comment by lidel** [comment]
> Why go-ipfs and not js-ipfs?

@mojoaxel  maturity, feature set and general performance when run as a background service.  At this time go-ipfs is easier on CPU and provides `dhtclient` mode which decreases ambient bandwidth use (key characteristics of something that is expected to run in background all the time).

**Comment by whyrusleeping** [comment]
@olizilla Yeah, thats a good start. We also might want to run it with a lowered connection count.

@magik6k do we have an init profile that would work well for this?

**Comment by magik6k** [comment]
There is the lowpower profile, but it might be a bit too aggressive - https://github.com/ipfs/go-ipfs/blob/master/repo/config/profile.go#L153-L158

**Comment by olizilla** [comment]
@magik6j @whyrusleeping something like a `--profile=desktop` that we could recommend for ipfs companion users would be rad. We've been suggestion people add `--routing=dhtclient` but a profile seems like a better fit. Should I open an issue for it on go-ipfs?

**Comment by whyrusleeping** [comment]
@olizilla yes, please do. We'll try and get that added before the next release.

**Comment by lidel** [comment]
cc https://github.com/brave/brave-browser/issues/819

**Comment by lidel** [comment]
Quick update:
Brave  [announced](https://brave.com/new-brave-browser-release-available-for-general-download/) first release of Chromium-based version. IPFS Companion works perfectly with Chromium-based Brave, and [this PR](https://github.com/ipfs-shipyard/ipfs-companion/pull/609) updates our docs to reflect that. I also updated https://github.com/ipfs-shipyard/ipfs-companion/issues/312#issue-274470185 to provide better intro to currently ongoing work.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-companion/issues/716
