### ISSUE TITLE
Announce IPFS companion releases on the ipfs.io blog?

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-companion#344]
...would be rad and maybe get more people using it

👍 👎 @diasdavid?

**Comment by diasdavid** [comment]
💯 👍

**Comment by alanshaw** [comment]
You do awesome [release notes](https://github.com/ipfs/ipfs-companion/releases) @lidel how do you feel about submitting a PR to https://github.com/ipfs/blog at the same time?

**Comment by lidel** [comment]
Neat idea! I'll do that, starting with next release. 
(With additional gifs and more exciting twist than regular RN, of course 🙃 )

**Comment by lidel** [comment]
PR Announcing IPFS Companion 2.2.0 is waiting to be merged: https://github.com/ipfs/blog/pull/156
