### ISSUE TITLE
Ability to Launch IPFS

### ISSUE THREAD

**Issue by atondwal** [ipfs-shipyard/ipfs-companion#352]
The web-extensions api supports launching native apps: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

**Comment by lidel** [comment]
Yes! This is already tracked in  https://github.com/ipfs-shipyard/ipfs-companion/issues/350 (Task 4)

**Comment by atondwal** [comment]
Oops, thanks, apparently my issue searching skills need work
