### ISSUE TITLE
Restarting ipfs daemon sometimes freezes the browser

### ISSUE THREAD

**Issue by magik6k** [ipfs-shipyard/ipfs-companion#360]
When restarting the local daemon (killing it and starting back after 10-30s), the browser will occasionally freeze for a few seconds.

ipfs-companion 2.1.0
Firefox 57.0.4
os/wm: Arch Linux/bspwm

**Comment by lidel** [comment]
I suspect this got fixed in past weeks.
Are you able to re-check with [v2.2.0beta1](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta) (from Development Channel)?
If the issue is still present, are you running multiprocess (`about:support` → "Multiprocess Windows")?

**Comment by magik6k** [comment]
so I've been running v2.2.0beta1 for some time on FF 58 now, and it is still an issue. Yes, it's running multiprocess.

**Comment by lidel** [comment]
Thank you, I will look into this as a part of stabilization efforts before v2.2.0 release.
(FYI we should have a new beta within a week)

**Comment by lidel** [comment]
I am following up on things and I am unable to replicate this. 

@magik6k  any change with latest version? ('beta' and 'stable' have the same code right now)

**Comment by magik6k** [comment]
on 2.2.0.8720 - I've had some hangs but it feels like they happen less often now. I've also noticed that I get these hangs when using 'Copy Public Gateway URL' from the context menu (might not be related to this issue).

**Comment by magik6k** [comment]
> are you having issues with pinning by any chance?

The pin button in the extension doesn't seem to do anything for me. (pin doesn't show up in `ipfs pin ls -t recursive`, there is no feedback but the browser doesn't hang)

> Is your node's HTTP API on the same machine or are you using a remote one?

It's on the local machine

> Slow/old laptop?

I'd call it slightly overkill workstation. IPFS node sits on hdd bcache-d on an nvme ssd, using badger datastore with about 24G of data in it.

**Comment by lidel** [comment]
Interesting.  Is there a specific IPFS Path that triggers the issue or is it purely random?

So far I've seen 'gui not being properly refreshed' once, when I was pinning root of a big directory tree that was not fully loaded into my node. Everything got back to normal after download finished, so I low-key suspect API stopped responding to new requests for `ipfs pin ls <path>`  when pinning of mentioned `<path>`  was in progress.

**Comment by magik6k** [comment]
`ipfs swarm peers` should be fast, `ipfs pin ls` may get really slow for mid-large repos, especially when called without `-t recursive` flag (mine repo has few 100k's of pins, pin ls can take minutes to finish)

**Comment by lidel** [comment]
Reopening, for some reason parameters added in https://github.com/ipfs-shipyard/ipfs-companion/pull/594 do not end up in the actual HTTP request sent by js-ipfs-api.
