### ISSUE TITLE
Jenkins Builds

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#364]
@victorbjelkholm noted that we should have ipfs-companion automatically built on jenkins, so that people can just download pre-built artifacts if they want to test bleeding edge features. 

### Prerequisites

just any Linux and Node will do

### Key Commands 
Install all deps & build the package: `npm run yarn-build` → `./build/ipfs_companion-*.zip`
Run tests: `npm test`

###  Tasks 

- [ ] set up Jenkins (@VictorBjelkholm ?)
- [ ] add Jenkins file (@lidel)

**Comment by VictorBjelkholm** [comment]
"set up Jenkins" should not be needed, if a `ci/Jenkinsfile` exists, Jenkins will pick up the project automatically. 

If we add a Dockerfile here, we can use docker to do the build, mounting the build directory to a local directory in the workspace, then archiving that artifact directory.

Something like this (might not work, haven't actually tried it myself):

### `Dockerfile`

```
FROM node:9.4.0-alpine
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/package.json
RUN npm install -g yarn
RUN yarn
COPY . /usr/src/app
RUN make build
```
### `ci/Jenkinsfile`

```
node(label: 'linux') {
  sh 'docker build -t ipfs-companion .' // builds the docker image
  sh 'docker run -it ipfs-companion make test' // run tests before build
  sh 'docker run -it -v $(pwd)/build:/usr/src/app/$BUILD_DIRECTORY ipfs-companion make build' // mount ./build to the build directory and builds ipfs-companion
  sh 'archiveArtifacts artifacts: 'build/*.zip'' // save the zip file that ends up in ./build
}
```

Replace `$BUILD_DIRECTORY` with where ipfs-companion places the final build

**Comment by olizilla** [comment]
Of note, the official node Docker images add `yarn` already: https://github.com/nodejs/docker-node/blob/df8782dfddf8c70663f0a7d19942120b1d6977a5/9/Dockerfile#L43-L60 

So it's possible to skip the yarn install step
```Dockerfile
RUN npm install -g yarn
```
...in our Dockerfile

**Comment by lidel** [comment]
We are now Jenkins-enabled 🚀 ✨ 

- https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-companion/activity?branch=master
