### ISSUE TITLE
Daemon is off but redirect is still enabled

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-companion#373]
I'm not being able to go to ipfs.io urls because the extension keeps redirecting me, even though the daemon is off.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/1211152/35877217-a7030ad0-0b6c-11e8-8652-2f1d9fb5115c.png">

Is this intended? 

I'm using version 2.1.0
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1211152/35877264-c742d690-0b6c-11e8-8106-2c2c11caa2f6.png">

**Comment by lidel** [comment]
Is Automatic Mode enabled on _Preferences_ screen?

**Comment by diasdavid** [comment]
It is:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/1211152/35900305-31ce4cae-0bc9-11e8-9158-23a988c728f3.png">
