### ISSUE TITLE
Custom dialog for window.ipfs ACLs (make it work under Firefox)

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#377]
Gist from @alanshaw's TODO  list in PR https://github.com/ipfs-shipyard/ipfs-companion/pull/333#issue-157965898:

> * Add a custom confirm dialog.  Firefox does not support `window.confirm` from the background process so it fails - **all access to `window.ipfs` on Firefox will be automatically denied**, however as a temporary workaround, Firefox users can use the manage permissions page to enable permissions after they have been auto denied
>    * Another reason this is needed is that we want to be able to grant access to all (or a subset of) the API for a given origin, `window.confirm` can't cover these UX requirements

It may be useful to note how other extensions handle confirmation dialogs  (repost from https://github.com/ipfs-shipyard/ipfs-companion/pull/333#discussion_r163708569): 

> I've noticed and found how Greasemonkey displays confirmation dialog (under Firefox):
> 
> https://github.com/greasemonkey/greasemonkey/blob/9ce5dabc74496fa6a631d991302ad4fd80730f1d/src/bg/user-script-detect.js#L76-L99
> 
> (HTML page loaded in new browser window with `'type': 'popup'`)

**Comment by lidel** [comment]
@alanshaw  are you looking into this, or should I mark it as "up for grabs" ?

**Comment by alanshaw** [comment]
I’m on it tomorrow morn
