### ISSUE TITLE
Autostart daemon

### ISSUE THREAD

**Issue by MCmodding4K** [ipfs-shipyard/ipfs-companion#379]
Hi,

it would be cool to start and stop the daemon from within the gui, like setting the path and then just clicking on a button within firefox/chrome

**Comment by lidel** [comment]
Good news, we have it on our roadmap! 👍 

We already track this  in https://github.com/ipfs-shipyard/ipfs-companion/issues/350, so I am closing this one as a duplicate. Please follow that one instead.
