### ISSUE TITLE
Pinning does not work on Firefox when using js-ipfs node

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#380]
Tested with 888d3cf
> ![2018-02-10-162729_1720x711_scrot](https://user-images.githubusercontent.com/157609/36063616-6699888c-0e7f-11e8-9709-8adda83b425f.png)

> ![2018-02-10-162559_752x427_scrot](https://user-images.githubusercontent.com/157609/36063591-308316be-0e7f-11e8-85dd-80847d559919.png)

We should either fix it or hide pin controls for now.

**Comment by alanshaw** [comment]
I think we need to hide the controls - there's no pinning in js-ipfs yet

**Comment by lidel** [comment]
Yeah, we need to hide it just like we hide WebUI :)
