### ISSUE TITLE
Error: Not able to stop from state: starting

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#407]
Error caused by transitory state of js-ipfs breaks logic related to `initIpfsClient`.

Found during tests of #395 while rapidly switching between embedded and external breaks:

> ![2018-02-26-160301_1011x542_scrot](https://user-images.githubusercontent.com/157609/36678784-f1d4fc80-1b11-11e8-8ae5-ba7a931e689f.png)

Error comes from js-ipfs: [src/core/components/stop.js#L17](https://github.com/ipfs/js-ipfs/blob/9f39a6f3b7b3c228dd6f3653a00cdb958d319385/src/core/components/stop.js#L17)

Perhaps `add-on/src/lib/ipfs-client/embedded.js` needs something like this?

```diff
-  await node.stop()
+  try {
+    await node.stop()
+  } catch (err) {
+    console.warn('[ipfs-companion] Error while stopping embedded js-ipfs node', err)
+  }
node = null

**Comment by alanshaw** [comment]
This should be fixed by https://github.com/ipfs-shipyard/ipfs-companion/pull/395/files#diff-32e24012b65c18d8aff3153451004bdcR20 when merged

**Comment by lidel** [comment]
Yup, #395 fixed this :cake:
