### ISSUE TITLE
Support inline installation for Chrome users?

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#408]
Ref. https://developer.chrome.com/webstore/inline_installation

**Comment by olizilla** [comment]
Yeah why not.

**Comment by lidel** [comment]
Google just solved this one for us :upside_down_face: 

> Starting today, inline installation will be unavailable to all newly published extensions.
> – https://blog.chromium.org/2018/06/improving-extension-transparency-for.html
