### ISSUE TITLE
Support Common &LAN Gateway Fail

### ISSUE THREAD

**Issue by daijiale** [ipfs-shipyard/ipfs-companion#425]
Sorry to make this issue about the problem that I meet：
        When I install ipfs-companion chrome extension，the ipfs resource opened in browser can be mapped to local gateway like ：**http://127.0.0.1:8080/ipfs/@ipfs_hash**
eg:
<img width="1118" alt="ipfs-companion-public-address" src="https://user-images.githubusercontent.com/6550752/37564218-39697fb6-2acc-11e8-83d7-ff4dfbfcb218.png">

The ipfs resource can be access normally，but when I use lan gateway , the IPv4 address like : **http://192.168.199.144:8080/ipfs/@ipfs_hash**  , to my mobile or other device accesses with the same lan network , it doesn't work。

And I try to map my local gateway to the common gateway like 121.42.192.17  ，it doesn't work as well，

Is the ipfs config limit this gateway map？

So I wonder how the resource bound to the **http://ipfs.io(208.101.48.171)** 

Looking forward to the  help and reply  @lidel

**Comment by lidel** [comment]
Hey, this does not sound like something related to ipfs-companion. 

I use similar LAN setup and works fine. 
Here is a quick checklist for you:
-  make sure your `go-ipfs` node is exposing port 8080 on a specific IP 
   - see [Addresses.Gateway](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addresses) key in node configuration 
      - by default it is limited to `127.0.0.1`, you want to change it to LAN IP or `0.0.0.0` (to listen on all interfaces) and restart daemon
- make sure there is no firewall/filtering running on your box or router.

I am closing this issue.  We use http://discuss.ipfs.io for support, so if the above hint did not help, please create a support topic there.
