### ISSUE TITLE
Can't copy link for SVG and PDF

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-companion#440]
On:

http://127.0.0.1:8080/ipfs/QmY9pfuxeojUKSKwLxuQimvwBGrNx9Vg8Jhb97kZwn2tXP/icons/glyph_small_cancel.svg

Copying the Canonical or Public Gateway Link doesn't work. It triggers the notification, but the clipboard remains unchanged.

**Comment by lidel** [comment]
Same for PDFs:

- https://ipfs.io/ipfs/QmWimYyZHzChb35EYojGduWHBdhf9SD5NHqf8MjZ4n3Qrr/Filecoin-Primer.7-25.pdf
