### ISSUE TITLE
Add site title label to permissions dialog entries

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-companion#462]
The window.ipfs permissions manager is rad. The only thing that could make it better is if added a hint to what site a particular ipfs path was. I just accidentally hit deny on a site i was working in, jumped to the management page to fix it and then guessed that the only one currently set to Deny was probably the one i needed to edit, which won't scale well.

<img width="1078" alt="screenshot 2018-04-18 10 26 24" src="https://user-images.githubusercontent.com/58871/38923665-0e9c1480-42f3-11e8-8c20-c439e0eb99d4.png">

If we could add a label to the permissions entries it'd really help. In chrome, the url bar autocompletes with web addresses and the site `title` as muted secondary text, to help disambiguate opaque urls.

<img width="811" alt="screenshot 2018-04-18 10 29 05" src="https://user-images.githubusercontent.com/58871/38923837-5cba371e-42f3-11e8-810d-5081595a96fb.png">

That kind of thing would really help here.

**Comment by jessicaschilling** [comment]
Marking this one as `status/blocked` until we bring back support for window.ipfs.

**Comment by lidel** [comment]
Closing due to https://github.com/ipfs-shipyard/ipfs-companion/issues/589#issuecomment-712356448
