### ISSUE TITLE
HTTPS Protocol error with Ghostery 

### ISSUE THREAD

**Issue by calvinc64** [ipfs-shipyard/ipfs-companion#466]
![image](https://user-images.githubusercontent.com/5560381/39087188-c93d9e56-459d-11e8-97df-bae716a5f4f5.png)

If I use D.Tube, I get certain problem because the gateways are https ones... but my local one does not understand HTTPS... but the companion ext is still redirecting with https protocol in version 2.2.1 for chrome.

![image](https://user-images.githubusercontent.com/5560381/39087206-13de53b0-459e-11e8-8ac0-0e9b9dbff828.png)
(I did setup my own gateway with an http in the companion config.)

**Comment by lidel** [comment]
Interesting: I am unable to replicate this with v2.2.1: both Firefox and Chrome redirect and load content fine using a LAN IP of my non-HTTPS gateway.

I think what may be happening is some other extension or userscript is interfering with your requests, replacing HTTP ones with HTTPS. 

Are you able to replicate with no other extensions and userscripts running?
Try running test with `chrome --user-data-dir=$(mktemp -d)` for empty profile.

**Comment by calvinc64** [comment]
![image](https://user-images.githubusercontent.com/5560381/39089274-bc764e2c-45c3-11e8-968d-05eedb355527.png)
Ok, for all of us, that R using Ghostery addon, whitelist your Domains for IPFS... this did the Trick for me, because I found out that ghostery has an int. http to https.

**Comment by lidel** [comment]
Thank you @calvinc64.

I looked at it closer and Ghostery provides no documentation nor controls to disable this forced protocol upgrade. I think it is a bug – filled an upstream issue: https://github.com/ghostery/ghostery-extension/issues/44
