### ISSUE TITLE
IPFS Node Type - What is that?

### ISSUE THREAD

**Issue by slrslr** [ipfs-shipyard/ipfs-companion#470]
Hello,

in Firefox IPFS Node addon configuration is option: "IPFS Node Type" and i can pick either:

Embedded or External

Description: "External: Connect to an IPFS daemon over HTTP. Embedded: Run an IPFS node in your browser via ipfs-js *Experimental*!"

There is no link to explanation on what that mean so i can better decide which one to choose. I know bare minimum about IPFS. I only know some sites link to IPFS content and i want to participate in the network to help distribute files.

I already installed and running go-ipfs (https://dist.ipfs.io/#go-ipfs) on my Windows 10. I do not know what are disadvantages of external option and if/what to add into "IPFS Node Config" text area.

**Comment by lidel** [comment]
Thank you for raising this issue. 
I agree, we should  be better at communicating what Embedded node is and what are its limitations.

@slrslr  I created  PR #471, to address this. 
Please take a look and let us know if proposed documentation  improves things.

**Comment by lidel** [comment]
FYI "Read more" links are present in latest beta ([v2.2.2.9120](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.2.2rc1)):

>  ![screenshot_7](https://user-images.githubusercontent.com/157609/39521592-722a21e6-4e0f-11e8-9e02-d6723b7359f3.png)
