### ISSUE TITLE
Storing files of a few megabytes to window.ipfs.files.add hangs Firefox for a minute or more

### ISSUE THREAD

**Issue by interfect** [ipfs-shipyard/ipfs-companion#485]
I'm trying to store MP3 files in IPFS for https://github.com/interfect/ipfstunes by loading them into `Buffer`s and then `ipfs.files.add`-ing them. Everything works fine using in-page `js-ipfs`, but with IPFS Companion's `window.ipfs`, using either the embedded or external node, storing a song-sized file will hang the Firefox UI and make my window manager prompt me to kill it because it is unresponsive.

I don't seem to have this problem with tiny files.

**Comment by interfect** [comment]
To test, you can go to https://interfect.github.io/ipfstunes with `window.ipfs` enabled and hit browse under "Add songs" and try and add any reasonably sized MP3 file.

The hang occurs *before* the prompt to authorize access to `ipfs.files.add` appears.

**Comment by lidel** [comment]
Thank you for reporting this. I was able to confirm presence of described delay / high load in Firefox 60.
Chromium 66 does not manifest problematic behavior, it seems to be limited to Firefox, so its an upstream bug in either Firefox or [`ipfs-postmsg-proxy`](https://github.com/tableflip/ipfs-postmsg-proxy).

**Comment by lidel** [comment]
Quick [test of raw `port.postMessage`](https://github.com/ipfs-shipyard/ipfs-companion/files/2386800/ipfs-companion-issue-485-port-alone.zip)  (`runtime` webextension API) shows no issue there:




![screenshot_55](https://user-images.githubusercontent.com/157609/45598767-5c2c7e00-b9e1-11e8-9ef9-aaa928d780fd.png)
![screenshot_54](https://user-images.githubusercontent.com/157609/45598768-5c2c7e00-b9e1-11e8-9a05-380264faafbc.png)

**Comment by lidel** [comment]
@alanshaw just a quick check-in: do you experience similar slowdown on Firefox+Mac? ([test page](https://ipfs.io/ipfs/bafkreiboq6jbzb64pky652ezr3izgez4qtiwiwiecbdc6onxgkq4z5qpje))

Any thoughts on what could be triggering that problem? 
(If it is a bug in Firefox we want to create a MVP demo that can be attached to a new issue at Bugzilla.)

**Comment by alanshaw** [comment]
<img width="932" alt="screen shot 2018-09-17 at 12 32 26" src="https://user-images.githubusercontent.com/152863/45620745-cbec4880-ba75-11e8-9660-5f2a005542f8.png">

**Comment by lidel** [comment]
@interfect  fyi the fix for this was released in beta [v2.5.0.11550](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.5.0.11550), will land in stable soon.
