### ISSUE TITLE
Open preferences in new tab for vendor consistency

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#502]
_(This may be a prerequisite for #491)_

## Background

Preferences screen looks different in every browser:

- Firefox opens `about:addons` page with vendor-specific settings  and [embeds Preferences inline on the bottom of the page](https://user-images.githubusercontent.com/157609/41788493-010a931e-764c-11e8-9651-0938a9103127.png)
- Chrome opens it in [a bizarre overlay that is too small for advanced UI](https://user-images.githubusercontent.com/157609/41789646-554ffc9e-7650-11e8-83b6-6ea5fa68d5c0.png)
- Firefox for Android opens it in a new tab

:carousel_horse: 

## Change

Always open _Preferences_ in a new tab: 
- a single UI for all vendors, no need for Chrome-specific styles
- bigger canvas enable us to design intuitive interfaces for advanced features as multiple backends (#491)
- we can finally switch _Preferences_ screen to use [ipfs-css](https://github.com/ipfs-shipyard/ipfs-css)

**Comment by jessicaschilling** [comment]
If anyone (@lidel?) is willing to set up a skeleton of porting this content into its own tab, I'd be happy to tackle the styling.
