### ISSUE TITLE
How do you use this to upload/ pin a string to the ipfs?

### ISSUE THREAD

**Issue by MoreHotSauce** [ipfs-shipyard/ipfs-companion#522]
I know you can use ipfs.add(Buffer.from("<string>")) to get the ipfs hash. But how do you pin the string? I have ipfs companion installed on chrome and it set to embedded

**Comment by lidel** [comment]
Pinning was not possible with js-ipfs until v0.30.0, which was released just this week.
I already created an issue to enable support for pinning with embedded node (https://github.com/ipfs-shipyard/ipfs-companion/issues/522), so let's close this one as a duplicate.
