### ISSUE TITLE
window.ipfs.files.cp and files.mv scoping bypass

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#530]
(Below A and  B are reproducible with ipfs-companion v2.4.2)

----- 

#### Bug A: passing source and destination without wrapping them in array bypasses scoping

```js
window.ipfs.files.cp('/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX', '/destination.jpg')
// → No error, but file is created outside the sandbox, at real /destination.jpg

createSrcDestPre.args.before: ["/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX","/destination.jpg"] 
createSrcDestPre.appPath:     '/dapps/https/www.wikipedia.org/'
// no destination prefix:
createSrcDestPre.args.after:  ["/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX","/destination.jpg"]
```

How to fix?

- [ ] **A.a)** Always require sources and destination wrapped in array (throw error if `!Array.isArray(args[0])`)
- [x] **A.b)** Add support for both versions?
  - Fixed in https://github.com/ipfs-shipyard/ipfs-companion/pull/531/commits/109565fe0c187b72de45c4039e8d4c44367f04ad

#### Bug B: copying from /ipfs/ is broken due to unnecessary prefixing (passing source and destination in array)

```js
window.ipfs.files.cp(['/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX', '/destination.jpg'])
// → Error: file does not exist

createSrcDestPre.args.before: [["/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX","/destination.jpg"]] 
createSrcDestPre.appPath:     '/dapps/https/www.wikipedia.org/'
// the /ipfs/ source got (unnecessarily) prefixed, which produced error above:
createSrcDestPre.args.after:  [["/dapps/https/www.wikipedia.org/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX","/dapps/https/www.wikipedia.org/destination.jpg"]]
```

How to fix?

- [x] Do not prefix if source is a valid `/ipfs/` path (validate CID, if invalid, then prefix)? 
  - Fixed in https://github.com/ipfs-shipyard/ipfs-companion/commit/e16709c6b38ab7c2d93acff6159877a8c3f7d509 

## Problem with tests/docs for  `files.cp` and `files.mv`

I noticed we test different API calls to `files.cp` and `files.mv` than ones in docs.

Right now only array-wrapped version is being tested:

- [interface-ipfs-core/js/src/files/cp.js](https://github.com/ipfs/interface-ipfs-core/blob/87a8f96b74987ab6d477dc73a91d9f32ff066267/js/src/files/cp.js#L50)
- [interface-ipfs-core/js/src/files/mv.js](https://github.com/ipfs/interface-ipfs-core/blob/87a8f96b74987ab6d477dc73a91d9f32ff066267/js/src/files/mv.js)
- [js-ipfs-api/test/files.spec.js](https://github.com/ipfs/js-ipfs-api/blob/73862da41b38fb0413e1a2fd2ca43436560b358a/test/files.spec.js#L336-L339)
- [ipfs-companion/test/functional/lib/ipfs-proxy/pre-mfs-scope.test.js](https://github.com/ipfs-shipyard/ipfs-companion/blob/e19f2319b46e892082e24051a4404c4c39b370b1/test/functional/lib/ipfs-proxy/pre-mfs-scope.test.js#L20)

.. but we advertise unwrapped version it in the SPEC docs:

- [interface-ipfs-core/SPEC/FILES.md#filescp](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filescp)
- [interface-ipfs-core/SPEC/FILES.md#filesmv](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesmv)

This means users probably run version that we don't have real tests for (at least that is the case for MFS exposed via window.ipfs). In most cases it does not matter, but there are edge cases such as window.ipfs where it makes a difference (see bug **A** vs **B** above)

@alanshaw  I would appreciate some feedback and sanity check on how to proceed. Should we add tests to interface-ipfs-core for both versions (implies **A.b**), refuse non-wrapped version and change SPEC docs (**A.a**), or maybe I misunderstood a deeper problem entirely?

**Comment by alanshaw** [comment]
@lidel 

A) The syntax recently changed to remove passing an array. Array syntax is deprecated but currently will work in js-ipfs-api - we need to update the code in companion that does the prefixing to either allow for both versions, or just the non array syntax

B) Yes that's a bug

**Comment by lidel** [comment]
@alanshaw  ack, added fixes and deprecation warning in https://github.com/ipfs-shipyard/ipfs-companion/pull/531, please take a look in spare moment

**Comment by lidel** [comment]
Fixed in https://github.com/ipfs-shipyard/ipfs-companion/pull/531
