### ISSUE TITLE
Linkify rendering issue

### ISSUE THREAD

**Issue by djdv** [ipfs-shipyard/ipfs-companion#539]
I'm currently on the beta version 2.4.2.10500 (9424acc)

Partial hashes seem to render incorrectly. I noticed the body of one of my emails looked wrong with this string
```
file {
data: ...
metadata: /ipfs/Qm... | /ipns/Qm...
}
```
it's rendering like this in Gmail

![2](https://user-images.githubusercontent.com/13862850/43141826-e68f553c-8f24-11e8-829b-8c0a08f78344.png)

and as
![untitled](https://user-images.githubusercontent.com/13862850/43141984-53659f72-8f25-11e8-94b5-59996afcf5b3.png)

when viewed as a txt file

**Comment by lidel** [comment]
Ack, this is a side effect of Linkify  – an invasive experiment that mutates DOM. 

[note to self] fix for this: 
- linkify should just ignore `<pre>`  blocks (high now we only ignore styled ones, but it is not enough)
- linkify should not run on if content-type is text/plain ([sample](https://ipfs.io/ipfs/QmYzJSSTaPo4mNywrZ2QwNzoyEqDGzya3YfNUJCodbvZze/string.txt))

**Comment by Stebalien** [comment]
Similar issue: "ipfs cat /pfs/QmId" renders as "/ipfs/QmId". Example:

ipfs cat /ipfs/QmId

(note: "ipfs cat /pfs/QmId" renders fine because my `i` isn't actually an `i` :smiling_imp: ).

**Comment by lidel** [comment]
FYI the fix landed in [v2.4.4](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.4.4). :+1:
