### ISSUE TITLE
window.ipfs undefined on some websites

### ISSUE THREAD

**Issue by Hazae41** [ipfs-shipyard/ipfs-companion#543]
window.ipfs is undefined on this website; I don't know why; on all browsers.
http://www.jeuxvideo.com/

**Comment by lidel** [comment]
It is a security [feature](https://ipfs.io/ipfs/QmVnLkRxWWv2xiPKeQy6re1zCepzX7YXUiq5fESkd1j8bC/bug_or_feature.jpg).

**tl;dr** `window.ipfs` is available only in [Secure Context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), and `http://` (unencrypted)  website different than localhost is not one. 

See https://github.com/ipfs-shipyard/ipfs-companion/issues/476 for more information.
