### ISSUE TITLE
Ability to get a hash for a remote file

### ISSUE THREAD

**Issue by ramined** [ipfs-shipyard/ipfs-companion#545]
It'd be great to be able to right click a file I can normally save-as (let's say a remote jpg or video) and get the hash. I would like to do this without downloading the file first. Is this doable?

**Comment by lidel** [comment]
I am afraid it is not possible: hash is generated by running hash function over the raw data.
We are unable to generate a new hash without downloading data first.

**Comment by lidel** [comment]
Not really on topic, but worth mentioning:

If you have the data downloaded and want to only generate a hash (without adding it to your IPFS node and announcing/providing it to the network) then there is a CLI command for that:

    ipfs add --only-hash [filename]

Resulting CID will be useful only if someone else on the IPFS network is already hosting that data, so I don't see how its useful in browser context where most of resources are not on IPFS yet.

Feel free to reopen if you can describe use cases for "download & generate hash & copy to clipboard"  without a step of adding it to IPFS.
