### ISSUE TITLE
Drag n' Drop to add files to IPFS not working

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#549]
firefox 61.0.1 on fedora 28 workstation
ipfs-companion Beta @ d46794a

Trying to drop a file just opens it in the browser.

**Comment by swedneck** [comment]
I am dragging from thunar.

**Comment by lidel** [comment]
Ok, I was able to get my hands on it and replicate. Basically drop element on upload page does not register drag&drop action and browser handles it instead by opening file via `file://` pseudoprotocol:

![peek 2018-08-06 15-05](https://user-images.githubusercontent.com/157609/43718216-4638e7d6-998a-11e8-94d3-65053304e578.gif)
