### ISSUE TITLE
Feature: improved right click menu

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#550]
Right now the right click menu can add items to ipfs, but it still copies the path of the page itself. I think it should instead copy the path of whatever you right click on, and also should not show the `add to ipfs` option if it's an ipfs link or (if feasible) already an ipfs object.

**Comment by lidel** [comment]
Closed in https://github.com/ipfs-shipyard/ipfs-companion/pull/574 :ok_hand: 
(Kept "Add to IPFS" as it  may be still useful if user want to add some content to own node while redirect was manually disabled. Worst case scenario it is no-op.)
