### ISSUE TITLE
Incompatible with Firefox 52.9.0

### ISSUE THREAD

**Issue by jvw1954** [ipfs-shipyard/ipfs-companion#556]

**Comment by lidel** [comment]
Mozilla deprecated Add-On SDK  in Firefox 53 and replaced it with WebExtension APIs:

- Legacy  versions of this add-on (`1.x.x`) were based on deprecated SDK. 
While it is not maintained nor supported anymore (thus I am closing this as wontfix), one can inspect, build and install it using codebase from [legacy-sdk](https://github.com/ipfs/ipfs-companion/tree/legacy-sdk) branch.
- For historical background on why we had to rewrite see [Issue #20: Move to WebExtensions](https://github.com/ipfs/ipfs-companion/issues/20).

I strongly suggest updating to the latest Firefox if you want the best user experience with IPFS integrations.
