### ISSUE TITLE
Feature: option to automatically copy url when adding to ipfs

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#576]
> Part of UX improvements for sharing local files (#342)

If you want to add something to ipfs and share it, it's annoying to have a tab open with the object and then have to click a button to copy a URL.
There should be an option on the settings page to automatically copy the canoncial/public gateway URL to clipboard and not open the object in a new tab.

**Comment by jessicaschilling** [comment]
I believe this is already implemented as described -- closing this issue, but please re-open if needed. Thanks!
