### ISSUE TITLE
Feature: Add to ipfs with custom filename.

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#578]
For both images and selected text.

**Comment by lidel** [comment]
- **images** are now added to MFS (https://github.com/ipfs-shipyard/ipfs-companion/pull/810) and user can easily tweak filename there before sharing ([v2.10.0](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.10.0))
- **selected text** improvements are tracked in #837
