### ISSUE TITLE
Bug: Adding images to ipfs sometimes adds the entire page instead

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#579]
For example, try right clicking the github logo and adding it to IPFS.

**Comment by lidel** [comment]
Thank you for reporting this!
Already tracked in https://github.com/ipfs-shipyard/ipfs-companion/issues/351 (but your title was beater so copied it there :+1: )

**Comment by lidel** [comment]
I thought this is duplicate of https://github.com/ipfs-shipyard/ipfs-companion/issues/351 but I think it is separate UX problem.


When image is also a link "Add to IPFS" picks URL of  a link. 
I guess user's expectation is to add image instead, so URL lookup heuristic should be changed.
