### ISSUE TITLE
Buggy redirect if gateway at port 80

### ISSUE THREAD

**Issue by TUSF** [ipfs-shipyard/ipfs-companion#580]
So I've set up my local webserver to serve up URLs starting with `/ipfs/` or `/ipns/` to just proxy pass to my IPFS gateway. This way I can just use localhost, without the port number after it showing.

Unfortunately, IPFS Companion seems to **_loath_** this, as it ends up deciding to redirect me to port `0`, instead of port `80` like it should. I even explicitly type out `http://localhost:80` (which later turns into `http://128.0.0.1:80`), but when I come upon an IPFS link, I'm redirected to port 0, for whatever reason.

Using Chromium 69, by the way.

**Comment by lidel** [comment]
Thank you for reporting this!
I can confirm, this bug is specific to Chrome (reproduced in Chromium 67).

**Comment by lidel** [comment]
Hey @TUSF, a fix for this landed in the latest Beta: [v2.5.0.11550](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.5.0.11550)
Are you able to take it for a spin and let us know if the problem is solved? Thanks!
(Remember to uninstall or disable Stable version first).

**Comment by TUSF** [comment]
Sorry forgot to reply here, @lidel 

The latest beta works just fine on my end.
