### ISSUE TITLE
Easy pinning of websites

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs-shipyard/ipfs-companion#581]
Would be amazing if ipfs-companion could automatically see that it's a dnslink-hosted website and provide some means for pinning the website when visiting.

Bonus-points if directories within a website could be pinned as well, so users don't have to pin an entire archive, just the parts the user cares about.

Credit to wongarsu on HN for this idea https://news.ycombinator.com/item?id=18008450

**Comment by lidel** [comment]
I am quite sure Companion.. already does that :) ?

When you are on any IPFS-enabled site (`/ipfs/` or `/ipns/`) clicking below item will create a recursive PIN for the current path.  In case of IPNS it will pin the current snapshot ([following pin](https://github.com/ipfs/go-ipfs/issues/4435) is not yet a  thing)


> ![screenshot_24](https://user-images.githubusercontent.com/157609/45683078-af6a1200-bb42-11e8-9914-671b57f4a489.png)



I agree UI may not be intuitive enough: any ideas how we could improve it?
We were thinking about replacing low-level pins with MFS directory that could be managed via new WebUI.

See more thoughts on UI for "pinning" in https://github.com/ipfs/ipfs-gui/issues/10

**Comment by VictorBjelkholm** [comment]
Cool, did not see that at first!

Two questions regarding it. 

1) Does it allow you to pin sub-resources? For example, the Stack Exchange archive is huge, and I might just want to pin one directory inside of it.

2) Does it detect dnslink websites? https://ipfs.io for example

**Comment by lidel** [comment]
1. Clicking on it will create a recursive pin for the current path, so if you are in a subdirectory it will only pin from that level

2. Yes, pinning IPNS will pin current snapshot

Right now all it does is simple `ipfs pin add -r <window.location.pathname2ipfsPath>` but after the Files manager lands with new WebUI we plan to [make it easier to manage and change this pinning UI to add "pinned" stuff to  MFS folder instead](https://github.com/ipfs/ipfs-gui/issues/10#issuecomment-373928862).

**Comment by lidel** [comment]
I think we've answered all questions :) 
Mentioned pinning changes will continue in https://github.com/ipfs-shipyard/ipfs-companion/issues/415
