### ISSUE TITLE
Add automagical translation of Cloudflare gateway

### ISSUE THREAD

**Issue by npfoss** [ipfs-shipyard/ipfs-companion#583]
Cloudflare just announced an IPFS gateway! It would be cool for the companion to do the same thing for those URLs as it does for ipfs.io. This also has the added bonus of reducing the load on ipfs.io servers.

Source: https://blog.cloudflare.com/distributed-web-gateway/

**Comment by lidel** [comment]
It.. should work out of the box  :gift: :sparkles:   :thinking: 

Companion automagically detects IPFS resources at public gateways (including Cloudflare's) and redirects requests to your locally running node:
- https://cloudflare-ipfs.com/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
  → http://127.0.0.1:8080/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR

@npfoss are you able to double check? 
If the above redirect does not happen for you, it looks like a bug.

**Comment by swedneck** [comment]
Those links redirect fine for me.

**Comment by npfoss** [comment]
Double checked, and I was just wrong before. Disregard. Thanks!
