### ISSUE TITLE
Redesign of Page Actions

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#587]
(Ideas extracted from https://github.com/ipfs-shipyard/ipfs-companion/pull/532#issuecomment-406620802 and #508 )

![screenshot_9](https://user-images.githubusercontent.com/157609/45751268-27533d80-bc12-11e8-8716-f6d7d2bfe1a4.png)

Initial assumptions / updates to the above mockup:

- **URL** → Rename to "Public URL" and use domain name of public gateway (for easy copying)
   - Rationale: URL of custom gateway is already in location bar, no need t duplicate it
- **PATH** → shows Canonical (IPFS or IPNS) Path
- **CID** → shows raw CID of current page
  - IPNS is resolved to IPFS CID, which delivers closes #508 
  - This could be Base32 CIDv1 by default, which delivers https://github.com/ipfs-shipyard/ipfs-companion/issues/527 
- Revamped "Copy.."
  - Clicking on URL, PATH, CID would select entire thing to make it easy to copy it to clipboard
  - There should also be "copy" icon on the right that would do the same
  - Having the above most of menu items could be removed, saving space
- (optional) Pining menu item could be replaced with an icon\
- Note that in Chrome Page Actions are not available (they allow only Page or Browser ones) and we display these items in Browser Action menu. This UI should look good there as well.

Not sure how to represent "IPFS resource loaded via Custom Gateway" – it looks out of place.
Perhaps if we show full URL like this, there is no need for it at all? 

cc @ipfs-shipyard/gui

**Comment by jessicaschilling** [comment]
Closing this issue, since these have all been addressed elsewhere. Please feel free to reopen if necessary. Thanks!
