### ISSUE TITLE
Force redirection to a particular public gateway

### ISSUE THREAD

**Issue by rotemdan** [ipfs-shipyard/ipfs-companion#588]
Hi, sorry if duplicate, but I couldn't find a similar issue.

Is there a way to force redirection of **any** IPFS link, either pointing to a localhost gateway or to a known public gateway, to a particular public gateway. For example all of:

```
http://127.0.0.1:8080/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
https://www.eternum.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
```
Would be redirected to
```
https://cloudflare-ipfs.com/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
```
?

**Comment by lidel** [comment]
Sure, just  put  `https://cloudflare-ipfs.com` in "Custom Gateway URL" in _Preferences_

Note that if you are not running local node (no API) then you also need to disable "Automatic Mode" and manually enable redirect oto "Custom Gateway", otherwise redirect will get disabled when API is offline.

**Comment by rotemdan** [comment]
Thanks. I'm trying it out and it seems to work so far. I think the confusion was that it is named "Custom **Local** Gateway URL" so I assumed it wouldn't work putting a public gateway there (as, say, it possibly uses a special REST api etc.), and similarly I assumed I should use the "public" field for the public one and that should be an option to "force" it somehow.

I guess the wording can be improved since this seems like a reasonable use case (now that there are multiple high quality gateways available)?

**Comment by lidel** [comment]
Thanks, that is good feedback. 
In near future we want to simplify this and just have "IPFS Backends" with different capabilities.
That should make it easier to set up redirections like yours.
(Gathering ideas in https://github.com/ipfs-shipyard/ipfs-companion/issues/491)
