### ISSUE TITLE
window.ipfs ACL should match the http read-only / gateway API

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-companion#597]
go-ipfs exposes a subset of the API to the gateway as a public / read-only version of the regular API. The white list we use for window.ipfs should be derived from that list, if it isn't already.

Current definition of the read-only api https://github.com/ipfs/go-ipfs/blob/727bf49eff7ff61936aee6d4674ae3e7ad0aaddb/core/commands/root.go#L155-L187

**Comment by lidel** [comment]
I like the idea of having the source of truth in a spec and being able to assume both js-ipfs and go-ipfs follow that spec.

That being said, right now, the lack of `add` on the list makes this proposal bit problematic.
If dapps are unable to add data over window.ipfs, why would anyone use it?
Is there an upstream issue for go-ipfs about changing defaults or making this list configurable?

**Comment by lidel** [comment]
Closing due to https://github.com/ipfs-shipyard/ipfs-companion/issues/589#issuecomment-712356448
