### ISSUE TITLE
Upload does not work with ipfs-cluster

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#600]
> ![error](https://user-images.githubusercontent.com/157609/46430469-4f31bd80-c749-11e8-8ae7-b0bb1ac3dd86.png)

### How to Reproduce

Grab latest ipfs-companion and  ipfs-cluster. 
For the purpose of this bug it can just  run locally in ephemeral  docker:

```console
$  docker run -it --rm --net=host ipfs/ipfs-cluster
```

Try to upload with API port in Companion pointing at:
1.  go-ipfs (`:5011`) → OK
1.  ipfs-cluster  (`:9095`) → `SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data`

### The Actual Problem

TL;DR is that companion uses  js-ipfs-api  (HTTP API Client library), and the library decides how to parse response payload based on additional HTTP headers. 

Cluster does not seem to return `X-Chunked-Output` and that is why `chunkedObjects` in [this line](https://github.com/ipfs/js-ipfs-api/blob/afc57247c97830311a17ba4f7841faccd6e31c07/src/utils/send-request.js#L56) is false, which changes the flow and triggers parser error in [`streamToJsonValue`](https://github.com/ipfs/js-ipfs-api/blob/afc57247c97830311a17ba4f7841faccd6e31c07/src/utils/send-request.js#L76).

### How to Fix?

@hsanjuan IIUC a fix would be to add `X-Chunked-Output` (and `X-Stream-Error`?) to ipfs-cluster's response to match what go-ipfs does. 

See comparison below. 

| go-ipfs | ipfs-cluster |
| ---- | ---- |
| ![2018-10-03--20-10-52](https://user-images.githubusercontent.com/157609/46430347-011cba00-c749-11e8-9f5b-8367cb754423.png) |  ![2018-10-03--20-11-11](https://user-images.githubusercontent.com/157609/46430344-011cba00-c749-11e8-8757-2f4883e95331.png) |

**Comment by hsanjuan** [comment]
Will do @lidel ! Thanks

**Comment by lidel** [comment]
Re-tested and can confirm this is fixed in [ipfs-cluster v0.7.0](https://github.com/ipfs/ipfs-cluster/blob/master/CHANGELOG.md#v070---2018-11-01) :tada:

**Comment by hsanjuan** [comment]
@lidel actually it's still broken with chrome because header gets stripped because CORs is not set correctly by cluster. :/

**Comment by lidel** [comment]
@hsanjuan hm.. this surfaces an interesting discrepancy between browser vendors. 

I tested scenario where:

- go-ipfs v0.4.18 is at `127.0.0.1:5001`
- ipfs-cluster v0.7.0 is at `127.0.0.1:9095` 
  (run without NAT via `docker run -it --rm --net=host ipfs/ipfs-cluster:v0.7.0`)
- ipfs-companion v2.5.1.12010 has API port set to `127.0.0.1:9095` 

And.. quick upload in Firefox works fine even without CORS headers: 

| `:9095` in Firefox :angel:  |  `:9095` in Chrome :anger:  | `:5001` in Chrome :angel:  |  
| ---- | ---- | ---- | 
| ![ok-firefox-2018-11-06--15-56-52](https://user-images.githubusercontent.com/157609/48072630-423b3a80-e1dd-11e8-8466-5eb57539217b.png) | ![error-chrome-2018-11-06--15-57-13](https://user-images.githubusercontent.com/157609/48072629-423b3a80-e1dd-11e8-9f4b-e5b4b4aa717e.png) | ![ok-chrome-2018-11-06--15-57-13](https://user-images.githubusercontent.com/157609/48072627-41a2a400-e1dd-11e8-8483-3c31de64042b.png) |

**Comment by hsanjuan** [comment]
The inspector shows the `X-Chunked-Output` headers everywhere, but it Chrome Javascript doesn't see it unless the `Access-Control-Expose-Headers` is set accordingly. We'll have a better approach to headers in the proxy endpoint for the next release and fix this once and for all.

**Comment by hsanjuan** [comment]
@lidel as of cluster 0.8.0-rc1 this is finally really fixed. Can be closed.

**Comment by lidel** [comment]
Confirmed with `docker run -it --rm --net=host ipfs/ipfs-cluster:v0.8.0-rc1`, works as expected :+1:
