### ISSUE TITLE
Do not redirect IPFS resources if hostname is 'localhost:*'

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#604]
```
<deni> IPFS desktop opens localhost:5001/ipfs/[hash] and companion redirects to localhost:8080/ipfs/[hash]
```

### Background

This does not happen in companion alone, because it normalizes `localhost` to `127.0.0.1` to avoid mixed-content warnings in we browsers, and we already ignore gateways at `127.0.0.1`.

Test Link: http://localhost:5001/ipfs/QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa/

### Fix

U guess we probably should do both:
1. Companion ignores gateways on  `localhost`
2. Desktop opens links with `127.0.0.1`  instead of `localhost`

@hacdias thoughts?

**Comment by hacdias** [comment]
@lidel I think it would be better for Companion to ignore gateways on `localhost`. I know Electron can register specific protocol handlers (like `ipfs://` or `dweb://`) but as far as I've searched, I can't find information on how to open 'regular' URLs for a specific domain, which leads me to conclude that it is not easily possible.

**Comment by lidel** [comment]
@hacdias  what I meant was to normalize `localhost` to `127.0.0.1` in API and Gateway port settings.
Eg. if user enters API port as localhost:5001, it should be replaced with the IP version. 
(but yeah, on top of this Companion should ignore localhost)

**Comment by hacdias** [comment]
@lidel gotcha! I agree then 😄
