### ISSUE TITLE
Detect DNSLinks as IPFS resources in "public gateway" mode

### ISSUE THREAD

**Issue by hazae41** [ipfs-shipyard/ipfs-companion#605]
When accessing an IPFS website from a [CloudFlare's DNSLink](https://developers.cloudflare.com/distributed-web/ipfs-gateway/connecting-website/), the extension does not recognize it as an IPFS resource, and thus does not show options to pin it, copy cid, etc.

Example: https://rhaz.fr/

**Comment by Hazae41** [comment]
I think "etag" and "x-ipfs-path" headers could be used to solve this issue

**Comment by Hazae41** [comment]
I forgot to mention that this occurs only when using "public gateway" mode of IPFS Companion; otherwise, the URL is successfully rewritten to 127.0.0.1:8080/ipns/the.web.site/ and the actions are shown

**Comment by Hazae41** [comment]
Okay, it does not only occurs for CloudFlare DNSLinks, but rather all DNSLinks accessed from "public gateway" mode

Example: https://ipfs.io/

In normal mode: actions are shown
In "public gateway" mode: actions are not shown

**Comment by lidel** [comment]
I believe it is fixed in latest version:

![2019-08-03-224104_3440x1440_scrot](https://user-images.githubusercontent.com/157609/62416696-e6a0bf00-b63f-11e9-9620-bbeb8c9072a3.png)
