### ISSUE TITLE
IPLD Explorer Integrations

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#610]
Some initial ideas:

- [ ] Linkify IPLD paths (onclick opens in Explorer)
- [ ] Context menu item  ("Inspect CID", same onclick as above)
- [ ] Support  `ipld://` and `dweb:/ipld/` by opening them in IPLD Explorer that ships with WebUI

cc https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/11

**Comment by jessicaschilling** [comment]
Closing in favor of https://github.com/ipfs-shipyard/ipld-explorer/issues/55
