### ISSUE TITLE
Improve UX when API is unstable

### ISSUE THREAD

**Issue by fiatjaf** [ipfs-shipyard/ipfs-companion#614]
When browsing a web page that does 4 simultaneous `ipfs.dht.findprovs` and one `ipfs.object.stat` calls, sometimes the companion crashes.

I start seeing lots of `ERROR     engine: open /home/fiatjaf/.ipfs/datastore/004159.ldb: too many open files engine.go:258` in the daemon logs.

Then the web page calls to `ipfs` fail silently, I think.

The IPFS Companion status window starts showing everything offline, 
![2018-11-05-084545_156x181_scrot](https://user-images.githubusercontent.com/1653275/47996428-ab3c8880-e0df-11e8-8095-a3e924ed30cc.png)

and then if I restart the daemon I get 
![2018-11-05-084742_334x996_scrot](https://user-images.githubusercontent.com/1653275/47996480-dc1cbd80-e0df-11e8-81c0-edc82f5aee4a.png)

If I wait more, the status window comes back to normal, but in the meantime some, or all, of my `ipfs.dht.findprovs` have already failed silently.

**Comment by lidel** [comment]
@fiatjaf thank you for reporting thiswith all the details!

I see the go-ipfs part ("too many open files") is tracked in https://github.com/ipfs/go-ipfs/issues/5739, so let's keep this issue about how ipfs-companion should behave in such situations. 

- [x] the UI is faded out if API is unreachable (this seems to work as expected)
- [ ] idempotent notifications (there should be no duplicates)
  - potential fix: queue API polls (we should not make new status update calls if previous one is still pending) 

Is there anything else we should improve here UX-wise?

**Comment by fiatjaf** [comment]
Well, this is probably unrelated but I would like stuff being printed to the console when the Companion is doing work. Perhaps there could be a `debug` mode I could put the extension on so that it would start printing a lot of things? I don't know.

Currently (at least on Firefox) nothing shows up in the Network tab, nothing is printed to the console. Things that fail silently are very annoying, but I can't even know they're failing silently, maybe they're just not failing and taking a lot of time.

**Comment by lidel** [comment]
I agree! I've been playing with verbose logs that can also be filtered via _Preferences_ screen in https://github.com/ipfs-shipyard/ipfs-companion/pull/557.  The PR was parked due to a dependency bug, but I see that got released recently, so it may be a good idea to get back to it in near future :)

**Comment by lidel** [comment]
Closing updates:
- configurable logger namespaces landed in https://github.com/ipfs-shipyard/ipfs-companion/pull/712
- ipfs-companion requires HTTP API exposed by go-ipfs, and if it is unstable, we can't do much about it, however:
  - "too many open files" in go-ipfs is tracked in ipfs/go-ipfs#5739, seems to be mitigated
  - there is experimental work on embedded js-ipfs in Brave (#716), which does not rely on go-ipfs
