### ISSUE TITLE
Redirect opt-out per website

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#633]
When using things such as riot (matrix client) that rely on the domain to separate logins it gets very annoying to have to turn off ipfs-companion to avoid redirection to the local gateway (which would cause riot to use a completely different account than when it's served from the intitial domain). 
It would be nice to be able to blacklist certain domains from being redirected to the local gateway.

**Comment by lidel** [comment]
This sounds useful and easy to add.
Would appreciate some feedback:

- What would be the intuitive UI for adding a website to redirect opt-out list?
  - A list of hostnames on _Preferences_ screen?
  - A button in browser action?
  - How to name this feature? ("Redirect opt-out"?)

**Comment by swedneck** [comment]
I think the preferences screen is suitable, and maybe "Gateway redirect blacklist"?

Maybe while you're at it add an option for whitelist as well? The user would then have radio buttons for choosing between "Filter: None, Blacklist, Whitelist".

**Comment by da2x** [comment]
When IPFS times out, the user should be prompted to temporarily disable it for the current domain (24 hours?) and be redirected back to the web version.

**Comment by da2x** [comment]
Some websites should possibly be on the blacklist by default … 

* *.neocities.org (public; but their nodes have been broken since 2017-11; hosts large number of websites)
* *.shiftproject.com (private network; [source](https://twitter.com/ShiftNrg/status/1080616185991958528))
* *.mrh.io (private network; [source](https://www.reddit.com/r/ipfs/comments/a7wgfl/twoparter_on_hosting_a_site_on_ipfs_with_and/ec6ezzj/))

**Comment by lidel** [comment]
Privacy Badger as a prior art:

> ![2019-01-20--23-01-17](https://user-images.githubusercontent.com/157609/51446115-cc3f6d80-1d0d-11e9-9d7e-88f166c78288.png)

I think the second button is quite valuable. We could enable it on Beta channel only, and make it open https://github.com/ipfs/ipfs-companion/issues/new with site URL pre-filled in description.

**Comment by lidel** [comment]
Note to self:

- As noted in #662, subresources are easy to detect, and can be linked to specific "parent URL". We can apply rules of the root document to all sub-resources, even if those are loaded from different Origins. For example, if we disable redirect for d.tube, it should be disabled for `d.tube` but also iframes loaded from `emb.d.tube` and third party hostnames `foo.bar.buzz.tld`, solving the problem of "breaking DTube".

- We may look into making exceptions for `image`, `audio` and `video` types ([`ResourceType`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType))

**Comment by lidel** [comment]
WIP in https://github.com/ipfs-shipyard/ipfs-companion/pull/687 – just pushed the first stab at UX, would appreciate feedback, thanks!

**Comment by lidel** [comment]
Ready for testing: [v2.7.5.748 (Beta)](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.7.5.748)
