### ISSUE TITLE
Context action to "Add to MFS"

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#635]
> &lt;@whyrusleeping&gt; lidel: i would absolutely love a right click 'save to mfs' thing for ipfs companion
> i can haz? 

Cool idea! 
We've actually are been thinking about switching Upload and all "Add to IPFS" context actions to MFS.

Would appreciate some feedback:

- Should we still pin, or is presence in MFS is enough?
  (I'd say to not pin: MSF is enough, and if we remove file from MFS it can be GC'd)
- Where should we save them in MFS? I was bit worried about adding stuff to the root (`/`) as it may get noisy quite fast. Perhaps `/added-via-ipfs-companion/`? (looking for better name) 
-  Does it make sense to keep non-MFS versions in UI? My thinking is that we don't want duplicate entries, as they would clutter context menus.

**Comment by fiatjaf** [comment]
> Should we still pin, or is presence in MFS is enough?

No, don't pin! Pinning is a great maze of despair. Once pinned, you're guaranteed to never find that thing ever again, and also guaranteed to not be able to delete it if you want. But adding to MFS + actually download the object is ideal.

> Where should we save them in MFS? I was bit worried about adding stuff to the root (/) as it may get noisy quite fast. Perhaps /added-via-ipfs-companion/? (looking for better name)

I like this name.
