### ISSUE TITLE
Do not inject window.Buffer

### ISSUE THREAD

**Issue by BlackGlory** [ipfs-shipyard/ipfs-companion#637]
I found that some websites such as zhihu.com will use window.Buffer, Buffer injected by ipfs-companion would break the normal behavior of these websites. Buffer can be set elsewhere.

https://github.com/ipfs-shipyard/ipfs-companion/blob/50db9c08d5bf0e5297981ff474da07585aa8a8ce/add-on/src/contentScripts/ipfs-proxy/page.js#L6

**Comment by lidel** [comment]
Thank you for reporting this. Could you elaborate how it "break the normal behavior" of zhihu.com?
I don't think the website will actually be broken: if `window.Buffer` already exists it will be left alone.  You just won't be able to use `Buffer` implementation from ipfs-ompanion.

That being said, we are planning to stop injecting `Buffer` and to support `ArrayBuffer` as input argument in web browser contexts: https://github.com/ipfs/interface-ipfs-core/issues/404

**Comment by BlackGlory** [comment]
@lidel 
Zhihu is a Chinese website, and triggering this abnormal behavior requires login, so it is quite difficult to explain. After enabling the extension, clicking on the "follow" button on the website will pop up an alert notice the operation failed. If window.Buffer is undefined, this alert will not appear.

According to my guess, there is an outdated fallback code inside the website that will detect window.Buffer, and its priority is higher than ArrayBuffer.
