### ISSUE TITLE
Mixed Content error when i view https website

### ISSUE THREAD

**Issue by feilongfl** [ipfs-shipyard/ipfs-companion#645]
It's a problem here,my website https://musing-pare-9e8d81.netlify.com/ it show me that 
```
Mixed Content: The page at 'https://musing-pare-9e8d81.netlify.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://feilong-server.lan:8080/ipns/feilong.ml/comic.json'. This request has been blocked; the content must be served over HTTPS.
``` 

gateway
```
~/c/dist on master ◦ ssh feilong-server.lan 21:53:43
feilong@feilong-server.lan's password:
Last login: Thu 12月20日 20:59:53 2018 from 192.168.2.21
Welcome to fish, the friendly interactive shell
feilong@feilong-server ~> ipfs --version
ipfs version 0.4.18 
```

settings
gateway: `http://feilong-server.lan:8080`
api: `http://feilong-server.lan:5001`

**Comment by lidel** [comment]
Hi, this error comes from web browser. To remove Mixed Content warning you need to enable HTTPS (encryption) and switch to `https://feilong-server.lan:5001` or run node at the same machine and access it via `http://127.0.0.1:5001` (local server does not require encryption).

More info: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
