### ISSUE TITLE
Redirection toggle in popup menu

### ISSUE THREAD

**Issue by swedneck** [ipfs-shipyard/ipfs-companion#647]
It would be handy to be able to disable/enable redirection to the gateway quickly from the popup menu, like you can with the global toggle.

**Comment by lidel** [comment]
Hm.. one already can disable redirect via this menu item:

> ![2019-01-08--00-01-09](https://user-images.githubusercontent.com/157609/50798399-854a8480-12d8-11e9-8894-93b1a137fc84.png)


I agree it is not very intuitive :) Should we rename it to something else?
Or are you suggesting moving it from menu to an icon next to the global toggle?

**Comment by swedneck** [comment]
Yeah that's a bit unintuitive, i'd presume that public gateway simply means it will redirect any page to the public gateway rather than 127.0.0.1:8080.

I would put it next to the global toggle, although i'm not sure what icon to use.

**Comment by lidel** [comment]
@swedneck does any of [these icons](https://ipfs.io/ipfs/QmTiZFUkqh1taZfhxam5YyG51b4gVoym5948bnCvSnoerk/) fit, or should we design a new one?

cc @olizilla for UX sanity check :)

**Comment by swedneck** [comment]
I can't find any icon there that really feels like it fits..

![image](https://user-images.githubusercontent.com/40505480/50912700-12a1ec00-1433-11e9-9c9f-8f5ba1fe873b.png)
How about something like this?

**Comment by swedneck** [comment]
It could also work to just rename it from "Switch to (custom|public) gateway" to "(Enable|Disable) gateway redirection" and otherwise leave it as is.

**Comment by lidel** [comment]
Some mockups below. Would appreciate sanity check. 


### Text-based global redirect toggle

| Enabled  | Disabled |
| ---- | ---- |
| ![on-2019-01-20--17-15-32](https://user-images.githubusercontent.com/157609/51445545-a5316d80-1d06-11e9-9e1a-338835ecd62f.png) | ![off-2019-01-20--17-15-55](https://user-images.githubusercontent.com/157609/51445547-aebad580-1d06-11e9-8d34-270b651b04d3.png) |

### Icon-based global redirect toggle 

Alone, text may be enough, but we plan to add per-site redirect opt-out (#633) so the icon for global toggle may be a better idea:

| Enabled  | Disabled |
| ---- | ---- |
| ![on-2019-01-20--22-59-30](https://user-images.githubusercontent.com/157609/51445593-66e87e00-1d07-11e9-96da-0b7db9f1a8b5.png) | ![2019-01-20--22-59-51](https://user-images.githubusercontent.com/157609/51445596-6b149b80-1d07-11e9-8573-6196e76fcae8.png) | 



Having that, menu could include a single text toggle for current site:

> ![2019-01-20--23-45-36](https://user-images.githubusercontent.com/157609/51446194-078e6c00-1d0f-11e9-9205-4664751c95e5.png)

**Comment by swedneck** [comment]
All of those look great, the last one looks perfect!

**Comment by lidel** [comment]
@swedneck  WIP in https://github.com/ipfs-shipyard/ipfs-companion/pull/687

**Comment by lidel** [comment]
Proposed toggle in action (https://github.com/ipfs-shipyard/ipfs-companion/pull/687#issuecomment-467243819): 
> ![redirect](https://user-images.githubusercontent.com/157609/53376263-0976cb00-395e-11e9-8536-d83d28ffeee9.gif)

**Comment by hacdias** [comment]
@lidel I can't provide a better glyph right now **but** I don't thing it looks really good between the other two. The other are kind of circular, big, heavy. On the other hand, the middle one is just a plain icon. I'd, at least, put it into a circle to match the other two.

**Comment by lidel** [comment]
Cannot be unseen:
![2019-02-26--14-54-36](https://user-images.githubusercontent.com/157609/53417717-74fc7f00-39d6-11e9-9691-ae7590e902ed.png)

**Comment by olizilla** [comment]
I am ded 😭 🤣

**Comment by lidel** [comment]
For what its worth _the hatboi_ goes away if we add another (lighter) glyph.
If it is something with similar stroke weight, things look more balanced:

![](https://user-images.githubusercontent.com/157609/51446604-cdc06400-1d14-11e9-861d-7a6ae96d0199.png)

Thoughts?

**Comment by olizilla** [comment]
i miss hatboi.

[redirect] [power] [settings] order wouldmake sense to me.  But i think you should give hatboi  a chance.

**Comment by lidel** [comment]
> #### [redirect] [power] [settings]
> ![2019-02-26--15-20-00](https://user-images.githubusercontent.com/157609/53419350-03becb00-39da-11e9-92ba-8d275c823029.png)

**Comment by lidel** [comment]
After some additional reviews it seems that the icon is causing more confusion than it should.
As a part of updates in https://github.com/ipfs-shipyard/ipfs-companion/pull/687#issuecomment-469369693 I switched the global toggle icon to a static "Gateway Redirect" menu item with an explicit switch toggle:


| redirect enabled | redirect disabled |
| ---- | ---- |
| ![1-dnslink-site-2019-03-04--19-18-32](https://user-images.githubusercontent.com/157609/53753917-c0b99780-3eb2-11e9-9d83-7380a65fc6a4.png) | ![2019-03-04--19-38-46](https://user-images.githubusercontent.com/157609/53755626-43dcec80-3eb7-11e9-9a3f-a86ad6420a34.png)  |

**Comment by lidel** [comment]
Ready for testing: [v2.7.5.748 (Beta)](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.7.5.748)
