### ISSUE TITLE
HTTPS API endpoint is downgraded to HTTP

### ISSUE THREAD

**Issue by yvt** [ipfs-shipyard/ipfs-companion#652]
The protocol part of the endpoint URL is always ignored and assumed to be `http`.

For example, if you specify `https://www.example.com`, all requests are actually sent to `http://www.example.com`. Although this usage scenario is very uncommon, this can unintentionally open possibilities for information leakage and MITM attacks.

**Comment by yvt** [comment]
I think, perhaps, this is the cause...? (Look closely at the spelling of `protocol`)

https://github.com/ipfs-shipyard/ipfs-companion/blob/17fa4e56f33e815469829193d910a00da66d34e1/add-on/src/lib/ipfs-client/external.js#L10

Here's the dump of the config object I managed to retrieve from the parameter of [`requestAPI`](https://github.com/ipfs/js-ipfs-http-client/blob/d40cb6c24120ba47615c754efb053c74bb7ac0ac/src/utils/send-request.js#L84):

```js
{
  "api-path":"/api/v0/",
  "user-agent":"/node-ipfs-api/26.1.2/",
  "host":"[redacted]",
  "port":"",
  "protocol":"http",
  "procotol":"https:"
}
```

**Comment by lidel** [comment]
@yvt wow that is a sneaky typo, great catch!
Mind creating a pull request with a fix? :)
