### ISSUE TITLE
Explore > multihash link is broken

### ISSUE THREAD

**Issue by lordcirth** [ipfs-shipyard/ipfs-companion#665]
The explore page explains the multiformat, and the string `0x12 = sha2-256` is a link to:
https://github.com/multiformats/multihash/blob/master/hashtable.csv which is a 404. I think the correct table is this one: https://github.com/multiformats/multicodec/blob/master/table.csv .

**Comment by fsdiogo** [comment]
Thanks @lordcirth!

This has been fixed in https://github.com/ipfs-shipyard/ipld-explorer-components/pull/12 and a new Web UI release is on the way.
