### ISSUE TITLE
Extension recommendation in Firefox 65+

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#673]
> Beginning in Firefox version 65, Firefox might occasionally recommend extensions based on websites you visit or ways you engage with the browser [..]
> 
> ![2019-01-26-06-19-31-425167](https://user-images.githubusercontent.com/157609/52054376-96e01e80-255c-11e9-9882-8f823c14ed90.png)
> 
> Source: https://support.mozilla.org/en-US/kb/extension-recommendations

Would be great if IPFS Companion got recommended when visiting `https://*.ipfs.io` and `https://*.dweb.link`

It is fairly new feature and process is a black box atm. Will revisit in near future.

**Comment by da2x** [comment]
I’d suggest reaching out to either ircs://irc.mozilla.org:6697/#amo or amo-featured@mozilla.org.

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-companion/issues/922
