### ISSUE TITLE
Bug: intercepting postMessage from ipfs-postmsg-proxy

### ISSUE THREAD

**Issue by hazae41** [ipfs-shipyard/ipfs-companion#675]
Using this module https://github.com/ipfs-shipyard/ipfs-postmsg-proxy
And following this tutorial https://github.com/ipfs-shipyard/ipfs-service-worker

Then doing
`createProxyServer(() => node)` from a service worker
`const node = createProxyClient()` from a website

Then using `await node.id()` from the website, IPFS Companion shows the permission request dialog and responds with the ID of IPFS-Companion

IPFS-Companion does this even if it is disabled

**Comment by lidel** [comment]
Thank you for reporting. Are you using Firefox or a Chromium-based browser?

**Comment by Hazae41** [comment]
Chrome

**Comment by lidel** [comment]
@Hazae41 by default `createProxyClient()` will use the same communication channel as `window.ipfs` 

If you want to talk to instance in Service Worker, you need to bind to  `navigator.serviceWorker` as in [this example](https://github.com/ipfs-shipyard/ipfs-service-worker/blob/b20b06afecda758774c600ff6285a6d790ee8081/examples/use-from-another-page/public%2Bsw/index.js#L11-L14): 

```js
node = createProxyClient({
  addListener: navigator.serviceWorker.addEventListener.bind(navigator.serviceWorker),
  removeListener: navigator.serviceWorker.removeEventListener.bind(navigator.serviceWorker),
  postMessage: (data) => navigator.serviceWorker.controller.postMessage(data)
})
```

Let me know if this helped.

**Comment by lidel** [comment]
Closing due to https://github.com/ipfs-shipyard/ipfs-companion/issues/589#issuecomment-712356448
