### ISSUE TITLE
Documentation on how to embed a video or image that is hosted on IPFS.

### ISSUE THREAD

**Issue by PurgingPanda** [ipfs-shipyard/ipfs-companion#683]
I cannot seem to find how to embed content that is hosted on IPFS. It would be helpfull to know how to embed a video on a page. Simply using an ipfs link like "ipfs://hash" does not seem to work.

**Comment by lidel** [comment]
@PurgingPanda  short answer is you use URL pointing at a public gateway: `https://<your-domain>/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR`. 

This way everyone will be able to load the content over HTTP, even people without IPFS client.  By using HTTP gateway you can add content to IPFS but load it using well-known HTTP semantics.  You can run `go-ipfs` on your own server, or  point at one of public gateways.

If you want to truly decentralize the distribution of your videos, you can either:

-  ask users of your website to install IPFS Companion browser extension (it will then automatically detect `/ipfs/<cid>` resources and redirect them to user's local node), 
- or set up [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway) to hijack requests for `/ipfs/<cid>` paths on your website and load it via js-ipfs (you can see Service Worker Gateway demo at http://js.ipfs.io/)

ps. I am closing this issue as this repository is not the best place for Q&A. To ask questions, discuss new ideas, or get support for problems check https://discuss.ipfs.io You can also hop on IRC (`#ipfs` on Freenode) for a quick chat.
