### ISSUE TITLE
[META] Upgraded UI for IPFS Companion

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#689]
#### <del>ETA April 2020:</del> :rofl: 
Next steps for this need to be an analysis of the entire discussion chain and breaking what hasn't already been addressed out into more discrete, workable parts.

#### Original issue text:
Let's use this issue as an open space for discussing how we could improve current UI,
namely the main menu displayed after clicking on Browser Action.

@ipfs-shipyard/gui

**Comment by lidel** [comment]
I've been looking into ways we could make actions specific to Active Tab more prominent.

Initials mockups:

| A | B  | C | 
| ---- | ---- | ---- |
| ![screenshot_2019-02-28 53101099-68d17700-3529-11e9-890b-0fd64b8a52e1 gif gif image 744 x 570 pixels](https://user-images.githubusercontent.com/157609/53589308-5ab9d100-3b8f-11e9-92ed-585421df4e27.png)  | ![updates-2019-02-23--21-30-03](https://user-images.githubusercontent.com/157609/53291434-9fbabd80-37b3-11e9-896f-7cd316973484.png) | ![companion-active-tab](https://user-images.githubusercontent.com/58871/53421062-dfacbb00-39d4-11e9-9316-c06dd559c6c7.png) |

@hugomrdias in https://github.com/ipfs-shipyard/ipfs-companion/pull/687#issuecomment-467542577
> I made a prototype which packs lots of ideas out of this PR scope
> 
> https://codesandbox.io/s/14y8r7qjo3
> 
> but basically i like toggles with explicit label and tooltip explaining everything like i'm 5. 
> I prefer label texts that don't change with state.

| Default | Expanded Node Info |
| ---- | ---- |
| [![screenshot_2019-02-28 codesandbox](https://user-images.githubusercontent.com/157609/53588657-c13def80-3b8d-11e9-9717-0a3a4f4468aa.png)](https://codesandbox.io/s/14y8r7qjo3) | [![screenshot_2019-02-28 codesandbox 1](https://user-images.githubusercontent.com/157609/53588711-e599cc00-3b8d-11e9-9364-41e8dc4a308b.png)](https://codesandbox.io/s/14y8r7qjo3) |

**Comment by lidel** [comment]
### New UI by Hugo

@hugomrdias posted well-thought mockup of complete rework in https://github.com/ipfs-shipyard/ipfs-companion/pull/687#issuecomment-467542577
> I made a prototype which packs lots of ideas out of this PR scope
> 
> https://codesandbox.io/s/14y8r7qjo3
> 
> but basically i like toggles with explicit label and tooltip explaining everything like i'm 5. 
> I prefer label texts that don't change with state.

| Default | Expanded Node Info |
| ---- | ---- |
| [![screenshot_2019-02-28 codesandbox](https://user-images.githubusercontent.com/157609/53588657-c13def80-3b8d-11e9-9717-0a3a4f4468aa.png)](https://codesandbox.io/s/14y8r7qjo3) | [![screenshot_2019-02-28 codesandbox 1](https://user-images.githubusercontent.com/157609/53588711-e599cc00-3b8d-11e9-9364-41e8dc4a308b.png)](https://codesandbox.io/s/14y8r7qjo3) |

Thank you for putting this up! I believe we will use a lot of this in following iterations.

**Comment by hacdias** [comment]
@lidel uuuh, I like it. I'd just change the reds to our fantastic blue and somehow give it a more interplanetary feeling. Otherwise looks really good.

**Comment by lidel** [comment]
Changes shipped in [v2.7.5.748 (Beta)](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.7.5.748)  borrow some of the above ideas:

| regular website | dnslink website | offline mode |
| ---- | ---- | ---- |
| ![github-2019-03-05--00-32-02](https://user-images.githubusercontent.com/157609/53770357-160b9e00-3edf-11e9-98c7-f2a5eca4fa8b.png) | ![ipfs-on-2019-03-05--00-32-32](https://user-images.githubusercontent.com/157609/53770368-1c017f00-3edf-11e9-96d8-aa5e87298f5f.png) | ![ipfs-off-2019-03-05--00-33-03](https://user-images.githubusercontent.com/157609/53770381-228ff680-3edf-11e9-9c87-5d117e01ec34.png) |

What would be the next thing to tweak?
Making the node info more compact?

**Comment by hugomrdias** [comment]
i revisited my prototype to add more ideas

https://codesandbox.io/s/14y8r7qjo3

**Comment by olizilla** [comment]
I love the new beta. +1 on clarifying "Redirect to gateway", though we still have some work to do to make that option make sense to new users. Perhaps _"Fetch sites via IPFS<sup>*</sup>"_ with a link to more info about how the HTTP to IPFS Gateway works, and that it will be activated by the existance of a _DNSLink_

Following on from the result of #687 I propose a small tweak / reversion to keep the parts of the menu that are always available together, and at the top of the list, and the part that is only available for a dnslink sites. That way the options appear in a stable position. We can drop the "tools" label from the current menu, as a i dont think it adds much. I imagine it like

- [header]
- Open Web UI...
- Share file via IPFS...
- Fetch sites via IPFS* [🔛...]

Current site
- Fetch `domain.com` via IPFS [🔛...]
- Copy https url &nbsp;&nbsp;&nbsp; _https://ipfs.io/ipfs/bafy..
- Copy IPFS address  &nbsp;&nbsp;&nbsp; /ipfs/bafy...
- Make page available offline*  [🔛...]

**Comment by olizilla** [comment]
Here's a mock

<img width="344" alt="screenshot 2019-03-05 at 14 45 21" src="https://user-images.githubusercontent.com/58871/53813356-5c9bdf80-3f55-11e9-9f6a-c1b996effab4.png">

**Comment by olizilla** [comment]
There are some really nice ideas in https://github.com/ipfs-shipyard/ipfs-companion/issues/689#issuecomment-469637081 too

**Comment by olizilla** [comment]
The key things i wanted to call out in my proposal are

- Replace "active tab" with some "x is available on IPFS!" excitement
- Keep menu items in the same position, so cluster things that are per site and things thar arent
- Fewer seperators is mo' better separators

it's kinda helpful to put "Copy CID" and "Pin CID" next to each other as it better highlights what you will be pinning, but how to explain what "Pin CID" will do is still difficult. I initially framed it as "Make available offline" as that's something the user might care about, but its not right. It's more like "Keep this snapshot in my local repo"

**Comment by lidel** [comment]
@hugomrdias @  https://github.com/ipfs-shipyard/ipfs-companion/issues/689#issuecomment-469637081: 
 - I like the idea of collapsing rarely used itemp under "More", but I am not a fan of hiding  direct access to WebUI.
    - IPFS Desktop provides direct links to Web UI screen, I believe we could the same.
Perhaps starting with subtle icons on the right? (at least Files, IPLD Explorer, Peers):
      > ![2019-03-05-160853_301x63_scrot](https://user-images.githubusercontent.com/157609/53814968-fe74f980-3f60-11e9-9917-1f5f41d5c2f6.png)
  - The File Share at the bottom is easily accessible, but takes too much space.
    We should come up with something closer to inlined version proposed by Oli:
    > ![2019-03-05-155946_302x31_scrot](https://user-images.githubusercontent.com/157609/53814382-cfaa5380-3f5f-11e9-93fd-fab9f3fe59b1.png)
 - IIRC file upload or drag&drop into popup menu did not won't work across vendors. That was the initial reason why quick upload screen in our extension is opened in a new tab. 


@olizilla  

We moved things around to keep redirect toggles together. If we move them back, we need to tweak language a bit: 
 - "IPFS" occurs too often in our UIs, which will be tricky to avoid :)
 -  "x is available on IPFS!" excitement is cool, but long hostnames are tricky if you can't truncate them: http://llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.co.uk/ 
    - Generic "This site is available on IPFS!" should do, and we avoid showing the hostname twice.
 - I agree  _"Redirect to Gateway"_  is too technical, and remains an empty phrase to regular people. _"Fetch sites via IPFS"_  is better, but it does not encompass ah-hoc IPFS resources found on random websites, and uses "IPFS" once more time.
   - I've been thinking about simplifying language on _Preferences_ screen and replacing _"Custom Local Gateway"_ with just _"My Gateway"_. 
     Perhaps redirect toggle could be labeled  _"Fetch with My Node"_ or  "_Fetch sites via My Gateway"_? Does it sound better at all? 
   - To simplify language even further, the label for per-site redirect opt-out could be renamed from _"Redirect on fqdn.tld"_ to generic  _"Disable on fqdn.tld"_  (that way the toggle would match Pin - off by default).  It would  not only disable redirect, but also stop injecting content scripts.
- I really like the idea of "Copy CID" providing context for "Pin CID"! 
  For now, there is a tooltip with explanation I adapted from [docs/concepts/pinning](https://docs.ipfs.io/guides/concepts/pinning/): 
  https://github.com/ipfs-shipyard/ipfs-companion/blob/27a62ad78aed9cb4040030fdbf25d585ee788202/add-on/_locales/en/messages.json#L79

**Comment by ericronne** [comment]
I hate to add noise to the conversation … but here's some noise anyway 😛 
A couple of very cursory tweak suggestions on @olizilla's mockup (these don't take @lidel's notes into account):
- Shifted banner elements to a left-right layout, which makes for a more uniform design, puts all of the buttons more or less in vertical alignment, and saves vertical space
- Recolored the gray (inactive) toggle to #65757C, to bring the contrast with white up to 4.5:1, for accessibility

![image](https://user-images.githubusercontent.com/9259185/53815885-2bf18100-3f28-11e9-8f11-e5a67756dcef.png)

Also, the contrast on the light gray text seems low. thx

**Comment by hugomrdias** [comment]
@ericronne  big +1

love all these iterations 

just one thing that bugs me a little, hierarchically 'Copy * ' can't be above 'Pin CID', imo not even in the same visual level.

if we want to give context lets add a tooltip explaining Pinning or put the multiaddr there like 'Copy CID'.

Can we name it 'Persist resource' with a tooltip saying 'Persist ipfs resource from the current tab to IPFS Companion node' ?

What's the user journeys or value that these 'Copy *' have?

**Comment by olizilla** [comment]
@hugomrdias I'm in favour of replacing the `Copy *` options with labelled fields as you have them in your proposal. I just wanted to offer up some minor tweaks to what we have now, as I find having the tools section split out at the bottom awkward (in the current look and feel).

The purpose of `Copy IPFS URL` them is to be able to grab a shareable IPFS http url. The brower URL bar will show `http://localhost:8080/ipfs/bafy...` which you can't share with folks who aren't using IPFS.

The purpose of `Copy CID` is to let the user grab the resolved CID for an ipns address. The site might point to the mutable `/ipns/ipfs.io` and there isn't an easy way to see which CID it was resolved to otherwise. It's lets the user copy and paste the value into the command line tool where ipns addresses and urls are not supported.

> Can we name it 'Persist resource

I am all in for a better name and explanation of *Pin* but it's such a weird concept that any name that makes sense is also wrong. It is literallly "Please dont delete this content that I already have locally at some arbitrary time in the future". I'm inclined to calling it Pin until we come up with a better API that lets a user deliberatly re-host a website for [week, month, for ever] as beaker does.

**Comment by olizilla** [comment]
@ericronne please give us all your feedback! Dont worrry about adding noise, we really want your thoughts!

**Comment by hugomrdias** [comment]
thank you for the "Copy *" explanation super useful  :) 

in my head "Please dont delete this content that I already have locally at some arbitrary time in the future" === "Persist content" (Persist is at least more of a common knowledge word than Pin) but i understand your point.

**Comment by lidel** [comment]
Toggle color tweaks in https://github.com/ipfs-shipyard/ipfs-companion/pull/692: 

| on/on/off | off/disabled/on |
| ---- | ---- |
| ![2019-03-06--14-57-50](https://user-images.githubusercontent.com/157609/53887351-5e7fa480-4022-11e9-8fac-631beaa9e3b4.png) | ![2019-03-06--15-03-21](https://user-images.githubusercontent.com/157609/53887367-64758580-4022-11e9-801b-b6d28cc6732e.png) |

**Comment by Hazae41** [comment]
How about using clean chips?

Preview: https://9j288y7rp.codesandbox.io/

[![Edit 9j288y7rp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9j288y7rp?fontsize=14)

![](https://i.imgur.com/MKbJVO3.png)

![](https://i.imgur.com/VyRpjeg.png)

![](https://i.imgur.com/FRMStlL.png)

**Comment by lidel** [comment]
I really like how this layout saves vertical space by grouping action buttons, but it does not seem to account for labels having different lengths in different languages: `Redirection`,` Open WebUI`, `Quick Upload` and `Pin resource` may not fit in a single line when translated.

Not sure how big problem would  that be. 
Maybe just something we need to think about while designing the look of those buttons.

**Comment by ericronne** [comment]
The pill buttons could wrap in those instances — creating a rag-right button layout — so that's probably not a big issue. Interesting stuff @Hazae41, thanks. I'm doing a visual audit of this and the desktop companion right now, actually, and some of what you have here could inform our direction. I, too, like the accordions.

**Comment by Hazae41** [comment]
> I really like how this layout saves vertical space by grouping action buttons, but it does not seem to account for labels having different lengths in different languages: `Redirection`,` Open WebUI`, `Quick Upload` and `Pin resource` may not fit in a single line when translated.
> 
> Not sure how big problem would that be.
> Maybe just something we need to think about while designing the look of those buttons.

It wraps correctly

| justify-content: 'none' | justify-content: 'center' |
| ------------- | ------------- |
| ![](https://i.imgur.com/vZdIqUP.png) | ![](https://i.imgur.com/QoMKMZ2.png) |

**Comment by lidel** [comment]
Right now, the menu looks like [this](https://github.com/ipfs-shipyard/ipfs-companion/issues/689#issuecomment-470123068):

![](https://user-images.githubusercontent.com/157609/53887351-5e7fa480-4022-11e9-8fac-631beaa9e3b4.png)

Problems:
- Actions look the same: Copying paths and URLs is presented in the same way as "opening Web UI" or "sharing files"
- We use bold text to highlight sharing files
- Some items cause menu to close when clicked (_Copy.._)
- Some items cause new page to be opened in a new tab: _Open WebUI, Share.._

## Changes to explore 

- change the way things are grouped (good exploration in previous comments)
- add icons that differentiate features
  - I imagine Sharing having consistent icons in Companion menu and [Web UI](https://github.com/ipfs-shipyard/ipfs-webui/):
    > ![2019-07-26--12-56-33](https://user-images.githubusercontent.com/157609/61947207-ec920280-afa4-11e9-97e6-c168bd3bb6f2.png)
- adding a visual indicator to items that open things in new tabs
  - this would remove surprises 
- Labels are not set in stone: if we have better metaphors we should consider changing language around some features (eg. replace "Pin" with "Co-host"). 
  - See issues about changing language around [Redirects](https://github.com/ipfs-shipyard/ipfs-companion/issues/741) and [Pinning](https://github.com/ipfs-shipyard/ipfs-companion/issues/742)

**Comment by jessicaschilling** [comment]
Adding notes on back-end control from https://github.com/ipfs-shipyard/ipfs-companion/issues/491 -- closing that issue in favor of this one, so please be sure to look through that issue before proceeding.

**Comment by jessicaschilling** [comment]
Update: Going to start noodling on some (but not all) of the remaining items in this discussion in a PR for miscellaneous UX improvements. Watch this space.

**Comment by jessicaschilling** [comment]
We'll have made substantial progress against most, if not all, of the items discussed here under https://github.com/ipfs-shipyard/ipfs-companion/pull/907. Keeping in mind the age of this thread, and how much has evolved since some of it was written, I'm going to close this and suggest that we open new (ideally more granular) issues for new thoughts that arise. Thank you!
