### ISSUE TITLE
Extension breaks in Chromium Dev Build 71.0.3578.98

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#715]
Reported in https://github.com/ipfs-shipyard/ipfs-companion/issues/666#issuecomment-485342795 by @nonchip: 

> not sure if it's related to this but looks like it by the APIs involved:
> 
> on chromium `Version 71.0.3578.98 (Developer Build) (64-bit)` the extension breaks on activation with the attached log from the background script: [nibjojkomfdiaoajekhjakgkdhaomnch-1555915381867.log](https://github.com/ipfs-shipyard/ipfs-companion/files/3102496/nibjojkomfdiaoajekhjakgkdhaomnch-1555915381867.log)

```
Unable to initialize addon due to error Error: 
Invalid value for argument 2. Property '.2': 
Value must be one of: [requestHeaders, blocking].
```

**Comment by lidel** [comment]
@nonchip Thank you for reporting this!  I was unable to replicate this error with  `75.0.3766.2` (so it is not related to #666). 

I believe this error is caused by [ipfs-companion requesting `extraHeaders`](https://github.com/ipfs-shipyard/ipfs-companion/blob/78ff3dade193f94084afaae1a8153ce5802ea9e0/add-on/src/lib/ipfs-companion.js#L98-L99) in [`onBeforeSendHeaders`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders).

Chromium 72 made a breaking change and added `extraInfoSpec`, which explains why 71.x failed to recognize it:

> ![2019-04-22--18-55-59](https://user-images.githubusercontent.com/157609/56512656-51fecf00-6530-11e9-8168-b81507a1aa8e.png)
> src: https://developer.chrome.com/extensions/webRequest

### How to fix?

There is [`minimum_chrome_version`](https://developer.chrome.com/extensions/manifest/minimum_chrome_version) which we should add to non-Firefox manifest to avoid issues like this in the future (especially when Manifest v3 things start landing..)

@nonchip are you able to provide some context why are you still using Dev Build of 71.x ? is it shipped with some package manager, or did you just had it around for testing purposes? (Its quite old, I think current Stable ix 73.x)

**Comment by nonchip** [comment]
@lidel yeah turns out i didn't do an upgrade in some time, and apparently my distro's maintainer for this package is a bit lagging behind, current version in my repo is 72.0.3626.121

**Comment by lidel** [comment]
Cool! Let's keep this open until we have `minimum_chrome_version` in Manifest
