### ISSUE TITLE
Setting for changing the Web UI address

### ISSUE THREAD

**Issue by chatch** [ipfs-shipyard/ipfs-companion#718]
I'd like to change the web UI address to http://127.0.0.1:5002/webui but I don't believe this is possible in settings.

My use case is when running js-ipfs as the backend for the external node type in companion. "jsipfs daemon" defaults are:
```
API listening on /ip4/127.0.0.1/tcp/5002/http
Web UI available at http://127.0.0.1:5002/webui
```

A web UI address field would solve this.  Or even better might be a preset to choose js-ipfs as a backend and have companion set both the api and web ui addresses automatically.

**Comment by lidel** [comment]
@chatch I believe setting `Gateway` and `API` ports to the ones exposed by js-ipfs is all you need. Assuming the default ports exposed by `jsipfs daemon`, _Preferences_ should look [like this](https://user-images.githubusercontent.com/157609/57333358-ebc3a000-711c-11e9-8291-2b8bed568716.png).

If I misunderstood your question, below is some additional context about webui.
Let me know if any of this helped, and how we can make it more intuitive. 

---- 

- The `/webui` exposed by js-ipfs (or go-ipfs) daemon is just a convenience [redirect to a hardcoded CID](https://github.com/ipfs/js-ipfs/blob/v0.35.0/src/http/api/routes/webui.js#L20) that represents latest Web UI available at the time the daemon was released.
- ipfs-companion's `Open Web UI` serves similar convenience purpose (extension ships with hardcoded  webui CID as well) 
- Daemon has a slower release cycle than this browser extension, so webui CID linked via daemon's `/webui` will be the same or older than the one opened from ipfs-companion. 
  - Example: right now both js-ipfs and ipfs-companion open 
[ipfs-webui v2.4.4](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.4) from `/ipfs/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub`,
so there should be no difference between them.
 - If there is a new Web UI release, ipfs-companion users will get it faster (without waiting for new js-ipfs/go-ipfs releases).

**Comment by chatch** [comment]
your right, setting the gateway has fixed it.  ui now opens doing that redirect mentioned above.

thanks!
