### ISSUE TITLE
whitelist 192.168.

### ISSUE THREAD

**Issue by icf20** [ipfs-shipyard/ipfs-companion#728]
![image](https://user-images.githubusercontent.com/17784575/59115975-b2b06280-894a-11e9-89d0-eae6d44f0ec1.png)

for some reason this IP is not white listed

**Comment by lidel** [comment]
Hi, this is a limitation of web platform and current definition of secure context:

- https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
- https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy

**tl;dr** only `127.0.0.1` can be used over unencrypted `http://`. You can use `192.168.*.*`, but need to set up encryption (`https://`)
