### ISSUE TITLE
Add "Copy Permalink" Options

### ISSUE THREAD

**Issue by DeedleFake** [ipfs-shipyard/ipfs-companion#740]
The dropdown has three copy items, as can be seen here:

<img width="325" alt="Screen Shot 2019-07-25 at 2 56 07 PM" src="https://user-images.githubusercontent.com/326750/61900819-63b79000-aeec-11e9-9df3-3303e42ecefe.png">

Unfortunately, when accessing a resource through an IPNS system, such as DNSLink, the top two both copy links that use IPNS, rather than the underlying IPFS CID. If I want a link that continues to work, regardless of IPNS changes, I have to hit 'Copy CID' and build it manually. It would be convenient if options were available for creating CID-based links instead of IPNS-based ones.

**Comment by lidel** [comment]
@DeedleFake very good idea!

It may require tweaking the text on existing labels.
I am not sure what would sound and good, would appreciate feedback:
 
- Copy Public Gateway URL (copies gw addr with `/ipns/` path or DNSLink)
- Copy Permalink (copies gw addr with resolved `/ipfs/` path)

What if we als o add matching path options:
- Copy IPNS Path
- Copy IPFS Path

How does this sound?

**Comment by DeedleFake** [comment]
Works for me.

**Comment by lidel** [comment]
@DeedleFake if you want to see this sooner than later, would you be interested in making a PR with this?

I believe steps are: 
- add new labels to the UI in [add-on/src/popup/browser-action/context-actions.js](https://github.com/ipfs-shipyard/ipfs-companion/blob/171fac24841a2c2e3d3c8563c0613605d03ec492/add-on/src/popup/browser-action/context-actions.js#L32-L47)
- implement logic behind new actions in [add-on/src/lib/copier.js](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/add-on/src/lib/copier.js)

**Comment by DeedleFake** [comment]
Should permalinks be direct IPFS links (`https://ipfs.io/ipfs/<hash of current file>`) or relative ones (`https://ipfs.io/ipfs/<hash of top-level IPNS redirect>/path/to/file`)? The above pull request uses relative ones, but I'm not sure which I prefer.

**Comment by lidel** [comment]
I'd go with relative ones (with full path), as it is more meaningful and enables exploration of specific website snapshot.
If someone wants the direct hash, they already have option for that: "Copy CID" :)

**Comment by jessicaschilling** [comment]
@deedlefake Just checking in on whether you might still be interested in PR-ing this? Thanks!

**Comment by jessicaschilling** [comment]
@deedlefake - apologies, I see you're waiting for review.
