### ISSUE TITLE
[Feature] Chrome - Allow in incognito

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs-shipyard/ipfs-companion#750]
Hi All,
I'm using ipfs-companion 0.4.22 with Chromium 76.0.3809.100 on Debian Buster.
In Incognito mode the window.ipfs is not available.
I noticed that the extension property do not provide an option to allow in incognito mode as most of the extensions provide.
Thanks

**Comment by lidel** [comment]
IPFS integrations were disabled in Incognito windows on purpose as it enabled tracking across incognito sessions. Detailed rationale can be found in https://github.com/ipfs-shipyard/ipfs-companion/issues/704 

@xmaysonnave are you able to describe your use case? 
Which specific features of IPFS Companion would you like to use in Incognito mode?
Thanks!

**Comment by xmaysonnave** [comment]
@lidel thanks to let me know the rationale behind your implementation.
If I understand well the problem is related to the local node running behind the browser who have no notion of incognito mode and thus allowing a potential leak.
If my understanding is correct it means that the currrent behaviour allow potential leaks but is not a browser related issue ?
Usually in dev mode I use incognito mode to bypass any cache side effect. Regular users who understand and use incognito mode could be troubled with such behaviour.
Thanks

**Comment by lidel** [comment]
Correct. Browser has a notion of "incognito", but IPFS node does not at the moment.

Running the same node in incognito opens a vector for IPFS-based tracking:

1. We know that IPFS Companion redirects subresources on `/ipfs/{cid}` paths to local IPFS node
2. Some website can embed an image under `/ipfs/{cid}`
3. Every visitor gets unique `{cid}`
4. Website can find out Peer IDs via `ipfs dht findprovs {cid}`

(Same problem with `window.ipfs`, which exposes the same node in and out of incognito) 

That is why we disable IPFS integrations in Incognito.

We may reopen this when IPFS node supports Tor transport, multiple identities, or if there is a way to signal to the gateway that a specific blocks should not be reprovided (a selective "read-only mode", partially discussed in #507).
