### ISSUE TITLE
Remote Node

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs-shipyard/ipfs-companion#751]
Hi All,
I'm currently writing a browser dapp who uses IPFS. As I want to minimize what I embed in my dapp I started to experiment IPFS Companion. It allow users to simply setup IPFS Companion. I setup a local HTTPS nginx proxy in front of my local node and it works great. However I tried to setup infura with no success.
Gateway: https://ipfs.infura.io
API: https://ipfs.infura.io:5001
Not sure here if my setup is correct but IPFS companion refuses to reach the api.
I got a notification indicating that the IPFS API is offline. Infura seems to be restrictive about their API. For example I tried to get ipfs.id() with ipfs-http-client but this operation is not allowed. I use this statement to verify that the node is alive.
Currently I can setup the API through my local node and the gateway to Infura (nice side effect to propagate any uploded files by the way).
Is it a regular behaviour ? Is there any plan to let the extension reach any remote gateway ?
The point here is really to benefit from what's embedded in the extension without duplicating any unnecessary libraries. Another benefit is the automatic updates provided by modern browsers.
Thanks

**Comment by lidel** [comment]
> Currently I can setup the API through my local node and the gateway to Infura (nice side effect to propagate any uploded files by the way).
> Is it a regular behaviour ?

Not a regular behaviour. 
We generally suggest users to install [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop) to run both API and Gateway on local machine.

If you ask users to point IPFS Companion at remote API and Gateway, then you don't need IPFS Companion. Your dapp should just use [js-ipfs](https://github.com/ipfs/js-ipfs) embedded on page and/or [js-ipfs-http-client](https://github.com/ipfs/js-ipfs-http-client) for talking to Infura API.

>  [..] tried to get `ipfs.id()`  with ipfs-http-client but this operation is not allowed [at ipfs.infura.io:5001] I use this statement to verify that the node is alive.

If this is the only blocker, you can replace `ipfs.id()` call with `ipfs.get('QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn')` check: connection is working if can we fetch the empty directory.

> API: ipfs.infura.io:5001
> Not sure here if my setup is correct but IPFS companion refuses to reach the api.

Infura is a third party service: if they decide to block required  API endpoints there is nothing Companion can do. Please open issue in Infura's tracker / support forum. 

I am closing this issue as it does not seem to be related to Companion.
