### ISSUE TITLE
Brave: Welcome screen should suggest embedded node as an option

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#767]
# Parent: #716  :lion: 

We should make default/suggested option (IPFS Desktp) more prominent, and note its still an experiment. Something like:

![Screenshot_2019-09-25 IPFS is the Distributed Web](https://user-images.githubusercontent.com/157609/65591945-d3e69e80-df8d-11e9-80e0-4582e1f0d840.png)

**Comment by jessicaschilling** [comment]
@lidel -- do we still want to do this?

**Comment by lidel** [comment]
I believe so, but after #843 and [Targeted Grant: Active local discovery in Brave](https://github.com/ipfs/devgrants/blob/master/targeted-grants/active-local-discovery-in-brave.md) land.

**Comment by lidel** [comment]
https://github.com/ipfs-shipyard/ipfs-companion/issues/967#issue-789971624
