### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Degget1986** [ipfs-shipyard/ipfs-companion#773]

**Comment by Degget1986** [comment]
I can no more enter my Gateway settings.....
I only want that my PS4 works before.... Since weeks i got Disconnect @ Online Games..... 
I think it's this IPS thing here

**Comment by cyber199** [comment]
IPFS is a system for sharing files, and ipfs-companion is a browser extension for Firefox and Chrome based browsers.  I believe you are looking in the wrong location at this particular part of the project doesn't target PS4.

Have you managed to install this on your PS4?  If so, try disabling or uninstalling the extension and seeing if it fixes the problem, then we will know it it's this or something else.

**Comment by lidel** [comment]
> (assuming this is about go-ipfs crashing cheap router, if that is not the case, please provide more details, closing for now)

@Degget1986  if your consumer router is unable to handle high numbers of connections, you can set limits in go-ipfs config: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#connmgr (try setting limits to 100-200)

If you continue to experience network issues, submit an experience report at https://github.com/ipfs/go-ipfs/issues, thanks!
