### ISSUE TITLE
Unable to install in Firefox for Android

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#779]
The fix for https://github.com/ipfs-shipyard/ipfs-companion/issues/761 is published to AMO as v2.8.6 

Unfortunately:
- ipfs-companion v2.8.6 requires Firefox 69 due to #771 and Firefox for Android is still at 68.1.1, so the latest release can't be used on Android yet
- v2.8.3 supports Firefox 68, however Android main page of an add-on offers latest (incompatible) version instead of older (but compatible) version (https://github.com/mozilla/addons/issues/1101)
  > ![CrDBu10](https://user-images.githubusercontent.com/157609/66031809-72ca4800-e504-11e9-8567-1fcf3037f0ac.png)
- Also, if user lands on wrong platform site, they will be offered desktop add-ons that didn’t work for them (https://github.com/mozilla/addons-frontend/issues/8701)

Keeping this issue open until either Firefox for Android 69 is released or https://github.com/mozilla/addons/issues/1101 gets fixed.

**Comment by mohe2015** [comment]
Unfortunately [there won't be a Firefox 69 for Android](https://www.ghacks.net/2019/04/26/the-future-of-firefox-for-android/). Instead Mozilla will slowly migrate to the new Firefox Fenix (which currently doesn't support installing addons)

**Comment by lidel** [comment]
This is unfortunate: I hoped the problem will resolve itself with the new release, but Mozilla shipped `68.x` instead. AMO  install page is still broken (https://github.com/mozilla/addons/issues/1101).

I am considering reverting https://github.com/ipfs-shipyard/ipfs-companion/pull/771 in a way that gets executed only in Firefox <69.

**Comment by lidel** [comment]
[v2.9.0.860 (Beta)](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.9.0.860) can be installed on Android (switched min. version to 68). 
We will land this to stable channel later this week.
