### ISSUE TITLE
Firefox 69 required? (No ESR compatibility)

### ISSUE THREAD

**Issue by Jake1702** [ipfs-shipyard/ipfs-companion#784]
Hi, is there a reason why on Mozilla's addon page it reports Firefox 69 is required? I am on 60.9.0esr and I am going to update to one of the 68 ESR branches, however even then it will be one version behind. I don't currently have any intention to get off the ESR branch. Is there a specific reason why the extension needs Firefox 69? (No ESR equivalent of that)

**Comment by lidel** [comment]
Thank you for raising this issue.  
There are two pieces to this puzzle:


### Why the latest release requires Firefox 69?

Firefox 69 shipped important fix for a painful bug around CORS, XHR and WebExtensions. 

This meant we finally could remove Firefox-specific workarounds, and use the same code as in Chrome and save bandwidth and speed up things a bit. 

More details in https://github.com/ipfs-shipyard/ipfs-companion/pull/771 (and https://github.com/ipfs-shipyard/ipfs-companion/pull/494 + https://github.com/ipfs-shipyard/ipfs-companion/issues/436).

### Number of ESR users

Given the low number of ESR users it really felt like worth bumping the minimum version.

### Why [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/) reports  Firefox 69 is required and blocks the install?

This looks like a bug in the addons website. 
IIUC it should detect ESR and provide an older-but-compatible version.

We [have the same problem on Android](https://github.com/ipfs-shipyard/ipfs-companion/issues/779), where latest version is still 68.x. 
I commented in  [this upstream issue](https://github.com/mozilla/addons-frontend/issues/8726), hopefully it will get addressed soon.

#### Potential workaround for ESR users

@Jake1702  until this is addressed [upstream](https://github.com/mozilla/addons-frontend/issues/8726), try to manually install v2.8.5 from https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/ :

> ![version-2019-10-08--19-39-06](https://user-images.githubusercontent.com/157609/66418884-572ed800-ea03-11e9-8d25-5e1028f603d1.png)

Let me know if that worked.

**Comment by lidel** [comment]
Hi @Jake1702, I think you should be able to use [v2.9.0.860](https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.9.0.860) on ESR now (switched min. version to 68). We will land this to stable channel later this week.
