### ISSUE TITLE
Language: replace "upload" with "import"

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#817]
## Current state

References to "upload" are everywhere

## Proposed change 

Rename labels and variable names from "upload" to "import" 
  (eg. "import to IPFS", `/ipfs-companion-imports/` directory on MFS, etc).

## Motivation

"upload to IPFS" brings some confustion, users reuse mental model of the old web suggesting that data is pushed to a third party server, while in truth data is just _imported_ to local node and _optionally preloaded_ to external one.

"import" is a safe alternative: Filecoin uses `import` term for similar purpose, and `ipfs add` may be renamed to `ipfs import` in the future (see https://github.com/ipfs/interface-js-ipfs-core/pull/552).

**Comment by lidel** [comment]
Mostly implemented in https://github.com/ipfs-shipyard/ipfs-companion/pull/810

**Comment by jessicaschilling** [comment]
Note: We'll replace "add" language with "import" language in Web UI as part of the work in https://github.com/ipfs-shipyard/ipfs-webui/issues/1206.
