### ISSUE TITLE
"redirect to gateway" unsets itself

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ipfs-companion#820]
Firefox Nightly (latest)
IPFS Companion (latest)

STR:

1. Open panel from action button
2. Toggle "redirect to gateway" to enabled
3. Close panel
4. Open panel

Expected: option is still enabled

Actual: is disabled

**Comment by lidel** [comment]
@autonome I was unable to reproduce with v2.9.0 and Firefox 72.0a1 (2019-12-02), 
Perhaps I am missing some info?

- Was Firefox profile an empty one?
- What type of node was used (embedded? external?)

**Comment by autonome** [comment]
Ah, I had IPFS Desktop daemon turned off! Started daemon and doesn't happen anymore.

**Comment by lidel** [comment]
Still, sounds like there is some confusing behavior around the toggle when daemon is off.
I see where you are coming from: daemon is off, but the toggle remains active and I can click on it, then it unsets itself when backend retries API call and fails:

![Peek 2019-12-03 14-34](https://user-images.githubusercontent.com/157609/70055560-0fc76100-15da-11ea-9911-8e7338c7c99b.gif)

Perhaps it should be faded out and inactive to remove any confusion?
