### ISSUE TITLE
Redirecting .ETH/ -> .ETH.LINK should use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by DavidBurela** [ipfs-shipyard/ipfs-companion#841]
**Platform:**
Windows
Microsoft Edge / Chrome,

**Issue**
Navigating to `almonit.eth/` redirects to `http://almonit.eth.link/`

**Expected result**
It should redirect to `https://almonit.eth.link/`

Defaulting to HTTPS makes sense, as .eth.link supports HTPS, and Edge/chrome will start warning that `http` sites are unsafe.

**Comment by DavidBurela** [comment]
If I had to take a wild guess of which line needs to be updated, I'd guess this.
I don't have an environment set up to do extension development, otherwise I'd attempt creating a PR for this

https://github.com/ipfs-shipyard/ipfs-companion/blob/c3f4c531514522bf11ca74ce878051480f8ad773/add-on/src/lib/ipfs-request.js#L409

**Comment by lidel** [comment]
Thank you @DavidBurela, fixed in https://github.com/ipfs-shipyard/ipfs-companion/pull/847

There is a small caveat to this:

### Limitation of wildcard certificate at `*.eth.link`

@chris-remus FYI there is an open issue with HTTPS on `*.eth.link` – is there an open issue for this somewhere? If not, where I can report below?

> 
> Gateway at `eth.link` uses LetsEncrypt certs that work only with `*.eth.link` and will fail for `*.*.eth.link`.
> 
> For example https://blog.khinsen.eth.link/ (loaded without ipfs-companion) produces certificate validation errors in both [Firefox](https://user-images.githubusercontent.com/157609/74569037-bd130980-4f79-11ea-8fbd-9d2e3cf43616.png) and [Chromium](https://user-images.githubusercontent.com/157609/74569197-1bd88300-4f7a-11ea-927e-15651c2eeb38.png). User can manually bypass the error and page will load fine, but its bad UX.
> 
>
