### ISSUE TITLE
This page -> Import to IPFS workflow is confusing

### ISSUE THREAD

**Issue by Mikaela** [ipfs-shipyard/ipfs-companion#850]
It begins understandably:

1. I open a website
2. I right click the website and choose Import to IPFS

but then it turns weird

3. I am taken to IPFS Webui directory such as `Files/IPFS-Companion imports/2020-02-25_175727` (well maybe this and 4. are understandable)
4. I double click the only file there
5. I am shown raw html inside IPFS WebUI without indication on how do I actually see the page I have imported?

![kuva](https://user-images.githubusercontent.com/831184/75265678-eba2a700-57f9-11ea-820c-7b7d47856f27.png)

I think that instead of 6 or in addition to it, I should see a pointer to https://ipfs.io/ipfs/Qmcu8NULAvtES4Tj4bCrrqxWoPEVsAmPmn1rvdnaJZEoCc (IPFS Companion README.md page imported to IPFS) and maybe there IPFS Companion should greet me and tell me that I am browsing a page imported to IPFS and link me back to the imported directorory page.

Possibly related: #91

**Comment by jessicaschilling** [comment]
Hi @mikaela -- thanks for describing this in such useful detail. What you're talking about is definitely an example of how the UX breaks based on work needed/discussed in https://github.com/ipfs-shipyard/ipfs-companion/issues/91. I'm going to close this issue in favor of that one, but link to your description here so we can track how the finished work can avoid the poor UX you're describing. Thanks!
