### ISSUE TITLE
Opt-in for loading latest webui from webui.ipfs.io.ipns.localhost

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#860]
With subdomain gateway on localhost (#853), users who want to use the latest Web UI can add `http://webui.ipfs.io.ipns.localhost:8080` to `API.HTTPHeaders.Access-Control-Allow-Origin` whitelist in go-ipfs config.

Idea: add an opt-in on Preferences screen (could be an experiment)

> ![](https://user-images.githubusercontent.com/157609/61490868-3465c800-a9ae-11e9-9108-9ed26593f43c.png)

The toggle would:

1. <del>append/remove mentioned origin to CORS whitelist in go-ipfs config (if its applied immediately) OR remove `Origin` header from requests coming from `webui.ipfs.io.ipns.localhost:8080` (will disable Origin check at go-ipfs)</del>
    - I don't think we need to add this to Companion. WebUI has pretty good instructions for users on how to set up headers: https://github.com/ipfs-shipyard/ipfs-webui/pull/1496
2. swap `webuiRootUrl` to open `webui.ipfs.io.ipns.localhost:8080` instead of `127.0.0.1:5001` (this includes `Open WebUI` in browser action menu, but also Files screen after successful file import)

**Comment by jessicaschilling** [comment]
@lidel Suggestion of minor tweak to the text?
_Replaces your node's stable version with the latest at /ipns/webui.ipfs.io (requires working DNS and a compatible back end)_

**Comment by jessicaschilling** [comment]
@lidel are we interested in following up on this one?

**Comment by lidel** [comment]
Yes, I believe adding a toggle that changes the URL behind menu item is all we need to do here:

> ![](https://user-images.githubusercontent.com/157609/61490868-3465c800-a9ae-11e9-9108-9ed26593f43c.png)

That is all.

Companion should not do any hacking around Origin or CORS:  WebUI has pretty good instructions for users on how to set up headers now: https://github.com/ipfs-shipyard/ipfs-webui/pull/1496

**Comment by jessicaschilling** [comment]
@lidel Do you have time? ;)

**Comment by lidel** [comment]
I was about to reply I don't have bandwidth and started writing tips for someone who would like to pick this up and i accidentaly ended up implementing it :man_facepalming:  see  #893
