### ISSUE TITLE
[Question] IPFS _dnslink redirect with HSTS site

### ISSUE THREAD

**Issue by ChrisLane** [ipfs-shipyard/ipfs-companion#874]
I've noticed that ipfs-companion doesn't redirect my website to the IPFS version even after adding an X-Ipfs-Path header.
My site has HSTS, is this why the redirect doesn't work?

**Comment by lidel** [comment]
IPFS Companion works fine with websites that have HSTS set up.
I suspect DNS record with DNSLink did not propagate yet OR IPFS Companion caches negative result (restarting extension or browser should help).
If you are okay with sharing the name of your website, I can take a look.

**Comment by ChrisLane** [comment]
The issue has persisted across browser restarts.
https://www.chrislane.com

**Comment by ChrisLane** [comment]
I've figured out what was going wrong here.

My site has a permanent redirect for "chrislane.com" -> "www.chrislane.com"
On Firefox, if I start typing out "chrislane.com" it will autocomplete for me to the full "chrislane.com", however behind the scenes, this probably actually autocompletes to "www.chrislane.com".
Since I only have a dnslink record of _dnslink.chrislane.com, the lookup for _dnslink.www.chrislane.com fails. After adding this record, the redirect works.

**Comment by lidel** [comment]
Glad you were able to figure it out!
Thank you for writing up details on your setup :pray: super useful to know how solve similar issues.
