### ISSUE TITLE
Trim down unused ipfs-css assets

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#881]
After switching to ipfs-css v1.x we ballooned the package a bit:

### v2.11 (last stable):

```
10M ipfs_companion-2.11.0_chromium.zip 
4M  ipfs_companion-2.11.0_firefox.zip
```

### v2.11.0.918 (latest beta):

```
19M   ipfs_companion_beta_ece3e0b_-2.11.0.918_chromium.zip
12M   ipfs_companion_beta_ece3e0b_-2.11.0.918_firefox.zip
```

Low hanging fruit is to remove fonts and icons that are not used:

```
 12.2 MiB  /ui-kit/fonts
564.0 KiB  /ui-kit/icons
```

Another problem is the size of WebUI, which is for now only bundled with Chromium/Brave:

```
 21.6 MiB  /dist/precache/webui.tar
```

But that's something we need to tackle upstream.

**Comment by jessicaschilling** [comment]
I was actually thinking of using the power and gear icons from ipfs-css in the main control screen, so thanks for the heads up ...

**Comment by lidel** [comment]
@jessicaschilling I mean, some fonts and some icons are being used, we just need to find a way of removing unused ones. (I'd love us to use power and gear as they are in ipfs-css instead of custom versions we have right now)
