### ISSUE TITLE
Progression page

### ISSUE THREAD

**Issue by Sovxx** [ipfs-shipyard/ipfs-companion#890]
**Is your feature request related to a problem? Please describe.**
I have opened this link http://bafybeiccfclkdtucu6y4yc5cpr6y3yuinr67svmii46v5cfcrkp47ihehy.ipfs.localhost:8080/frontend
When I click on "thumbnails", which is a 38 MB file (or folder ?), chrome is loading and loading and... loading.
There is no way to tell when it will be finished or if there are connected peers who have it.

**Describe the solution you'd like**
Have some page in IPFS companion showing the content(s) being loaded, the number of peers who have it complete and uncomplete, the progression and the speed.
Kind of like bittorrent.

**Describe alternatives you've considered**
Look at the status page and check how the bitrate changed compared to before I click "thumbnails", but it is not convenient and accurate.

**Comment by jessicaschilling** [comment]
Hi @Sovxx -- thank you for filing this issue! We have a pool of potential work right now related to various sorts of progress indicators, and this is a new spin on this idea. It's not clear how or when we'll be able to slot this work into the workflow between other projects, but this is really good information to start with. (Of course, if you're interested in contributing to a solution, this would be more than welcome!) Thanks again 😊

**Comment by lidel** [comment]
Thank you for writing this user experience report @Sovxx!
I'm closing this one to avoid duplicates – let's continue in already existing https://github.com/ipfs-shipyard/ipfs-companion/issues/727

**Comment by jessicaschilling** [comment]
@lidel Thanks for flagging the duplicate - that one slipped my mind.
