### ISSUE TITLE
Regression in HTTP recovery of background tabs

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#897]
If a browser is configured to open links via middle click in the background (without switching active tab), then #876 has unexpected sideeffect:

- Open https://ipfs.io/ipns/ipfs.io/blog/24-uncensorable-wikipedia/ in the background tab
- It loads and returns 404 error
- Companion recovers by updating _active tab_ to the correct URL, but the active tab is not the one that failed, but this one

Fix would be to find tabId that failed and explicitly update using explicit tabIt, instead of assuming it is active.

**Comment by lidel** [comment]
@abueide would you be interested/have time to tackle this one? :)

iirc all that needs to be done is `request.tabId` needs to be passed as the first parameter of every [`browser.tabs.update`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update) call we make in `ipfs-request.js`

**Comment by quevas13** [comment]
Hi,

I'm working on it.
