### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#902]
Various screens are lacking favicon:

- Welcome screen
- Preferences
- Share files via IPFS (quick-upload)

We probably could reuse one from https://github.com/ipfs/dir-index-html/pull/36 – 
@jessicaschilling  thoughts?

**Comment by jessicaschilling** [comment]
@lidel I'm seeing favicons on all those pages. Confused.

![image](https://user-images.githubusercontent.com/1507828/85794986-c1ec8480-b6f4-11ea-9c2a-d463e3e83fb4.png)

**Comment by jessicaschilling** [comment]
Update: Favicons display in Chrome, but not Firefox.

**Comment by lidel** [comment]
I guess when there is no explicit favicon defined in HTML loaded from browser extension Chrome fallbacks to extension's icon, and Firefox does not. So adding explicit definition should fix firefox.
