### ISSUE TITLE
Can no longer temporarily disable redirect in menu

### ISSUE THREAD

**Issue by NatoBoram** [ipfs-shipyard/ipfs-companion#910]
> **Describe the bug**
> A clear and concise description of what the bug is.

It's no longer possible to quickly prevent IPFS-companion from redirecting a public gateway's URL to localhost whilst keeping other interactions.

**To Reproduce**
> Steps to reproduce the behaviour:

1. Click on IPFS Companion
2. There's no "Disable direct" anymore.

**Expected behavior**
> A clear and concise description of what you expected to happen.

"Disable redirect" should be there.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - ???

**Additional context**
> Add any other context about the problem here.

This is very valuable to troubleshoot custom public gateways. If the extension is now all-or-nothing, then it's completely useless to any public gateway maintainer.

**Comment by jessicaschilling** [comment]
Hi @NatoBoram -- Global redirect toggle is no longer in the menu, but is still available in the preferences:
![image](https://user-images.githubusercontent.com/1507828/87354835-7b808d80-c51c-11ea-8cfc-1739cc6928f9.png)

**Comment by NatoBoram** [comment]
That doesn't really help. To maintain a public gateway, I need to be able to quickly switch off the redirection and turn it back on when I'm done. Otherwise, I have to turn off the extension completely, but that means I won't be able to test the IPFS API on an IPFS website from my public node.

**Comment by lidel** [comment]
@NatoBoram  I am often testing resources with and without Companion too, but I use Incognito mode for that, and that is what I suggest in your case too. You can open  Incognito mode via browser menu or keyboard shortcut – it is faster than toggling companion via its menu. 

Rationale: Companion does more than a simple redirect now (eg. network/http recovery amongst other things) and testing with disabled redirect alone can give you false results in some scenarios. You need to disable Companion to have confidence in testing. IPFS Companion is disabled  in Incognito mode, so you don't need to toggle anything to get redirect back, just close Incognito tab.

I hope this helps in speeding up your testing workflow. 

Unfortunately having two redirect toggles in main menu proved to be confusing to less technical users, so we are not planning on bringing it back.
