### ISSUE TITLE
Display release notes upon updating Companion version

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-companion#912]
As proposed in https://github.com/ipfs-shipyard/ipfs-companion/issues/662#issuecomment-658764395, send user to https://github.com/ipfs/ipfs-companion/releases/latest upon updating version of Companion.

**Comment by jessicaschilling** [comment]
@lidel -- we could use [`runtime.onInstalled`](https://github.com/ipfs-shipyard/ipfs-companion/issues/912) for this purpose, but we're already using that to display the welcome page. We could create two tabs, but not sure if that's simply too disruptive. Thoughts?

**Comment by lidel** [comment]
I think `/latest` will always link to the stable version, to make it work for Beta channel as well we should send user to version from manifest:

```js
`https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v${browser.runtime.getManifest().version}`
```

**Comment by jessicaschilling** [comment]
https://github.com/ipfs-shipyard/ipfs-companion/pull/913 will close this.
