### ISSUE TITLE
Add option to pin content locally?

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-companion#917]
Question from HackFS participant:
_When using the IPFS Companion extension, is there a way to create a button to let users pin this content locally?_

cc @autonome for clarification: We've got the pin toggle in the main extension menu (cube menu); is this instead referring to a right-click option when clicking on an item that could be imported to IPFS?

**Comment by lidel** [comment]
I remember this question, in the thread it was clarified the person meant a cross-origin button like those twitter/facebook ones from the past:

> ![2020-08-25--18-27-59](https://user-images.githubusercontent.com/157609/91201440-b8859580-e700-11ea-8163-b46f6ba3d331.png)

With #777 we moved away from injecting  anything into the page contexts, and the current climate on the web is is moving away from "facebook button".

So the short answer is no, there is no way to create such button atm.

----

That being said, one can pin the currently loaded resource via ipfs-companion browser extension, just like @jessicaschilling hinted at:

> ![2020-08-25--18-24-03](https://user-images.githubusercontent.com/157609/91201050-4614b580-e700-11ea-90d8-071f753f4543.png)

This is the only safe way of doing this without asking user to manually whitelist Origin via CORS etc. 

We will be revamping pinning UI in Companion after support for Pinning Services Integration lands (tracked in epic at https://github.com/ipfs/ipfs-gui/issues/91), #581  #525
