### ISSUE TITLE
Promoted Add-ons Pilot 

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#922]
[Mozilla announced _Promoted Add-ons Pilot_ program](https://blog.mozilla.org/addons/2020/09/09/introducing-the-promoted-add-ons-pilot/) which among other things, prioritizes human reviews and displays "verified" badge:

>  Developers will have all new versions of their add-on reviewed for security and policy compliance. If the add-on passes, it will receive a Verified badge on AMO and in the Firefox Add-ons Manager (about:addons). The caution label will no longer appear on the add-on’s AMO listing page.
>
> ![](https://blog.mozilla.org/addons/files/2020/09/existential-600x288.png)

Caveat:

> ou (or your company) must be based in the **United States, Canada, New Zealand, Australia, the United Kingdom, Malaysia, or Singapore, because once the pilot ends, we can only accept payment from these countries.** 

@protocol has US presence in form of a Delaware company, so all good.

I've signed us up, but the pilot program is limited to 12 extensions, so it is unlikely we will make into it, but let's keep this issue open so when gates open for everyone we can get the verified badge. 

> ![2020-09-15--14-12-14](https://user-images.githubusercontent.com/157609/93209500-80510000-f75e-11ea-94d0-54903893116b.png)

Sidenote: would be incredibly useful to have something like this at Chrome Web Store (cc @dotproto )

**Comment by dotproto** [comment]
Thanks for the tag. It's probably not surprising that we've also gotten similar requests from developers. I'm curious to see where this goes.

**Comment by lidel** [comment]
Closing this as Mozilla decided to close the program after the pilot:
https://blog.mozilla.org/addons/2021/01/21/promoted-add-ons-pilot-wrap-up/

@dotproto I still believe there is an opportunity to improve how things are, especially given how big Chrome Web Store is.

Perhaps there could be a program where extensions over N  users are automatically invited to some variant of "verified badging" process (which includes in-depth human code, privacy and security reviews/audits). 
N would be picked to make it free of charge, as it is in the best interest of the entire platform to audit the most popular extensions.

A paid version of the program could co-exist, for extensions with lower number of users, making it possible for companies and organizations to sponsor review/audit work before they hit required user base.
