### ISSUE TITLE
Unable to Process IPFS Request

### ISSUE THREAD

**Issue by xternet** [ipfs-shipyard/ipfs-companion#927]
Not working on Firefox (before it was).
Working on Chrome.

https://gateway.ipfs.io/ipfs/bafkreiewrj2pugsghd3flw2lk2fhvtmz6wipecnxep5qc5m3lfpf2mvjk4#ipfs%3A%2F%2Fqmyce6unnvdjgvjmhzretjkabttajzea3yecacjsjzjlzv%2F

**Comment by jessicaschilling** [comment]
Hi - this is a known issue in Firefox, which converts URIs to lowercase before Companion can intervene. As noted in the error page, you can use https://cid.ipfs.io/ to convert the original CIDv0 to a case-insensitive CIDv1 that Firefox will work with. We're also shipping a version of that error page, with clearer guidance, in the next Companion version. 

Closing this issue, but please comment if you have other problems. Thanks!
