### ISSUE TITLE
Don't pop up new tabs on updates

### ISSUE THREAD

**Issue by kallisti5** [ipfs-shipyard/ipfs-companion#933]
Yeah... I was mid-typing something **important** and ipfs-companion popped up a new window for an update release notes.
Please *DON'T* do this anymore.

I don't mind seeing release notes in the ipfs-companion extension (maybe red circle notification or something over the icon), but spamming users with pop-ups is a sure-fire way to get a bunch of uninstalls.

**Comment by kallisti5** [comment]
At minimum... this should be "opt-in" and **not** "opt-out"

![disabled](https://user-images.githubusercontent.com/100110/96603791-ff83a780-12b9-11eb-996f-87dc66388ae2.png)

**Comment by lidel** [comment]
Ouch, thank you for opening this issue and sorry for inconvinience :( 
We will definitely improve the default behaviour and remove surface for disruptions like the one you experienced.

@jessicaschilling thoughts on how we can make this less disruptive?

Perhaps we could add some icon to the header section in the popup menu?

Prior art from 1password:

> ![2020-10-20--17-31-36](https://user-images.githubusercontent.com/157609/96609102-72147780-12fa-11eb-99fd-058c8b6b4901.png)

when clicked:

> ![2020-10-20--17-31-58](https://user-images.githubusercontent.com/157609/96609132-79d41c00-12fa-11eb-943b-bd9947bda60e.png)

**Comment by kallisti5** [comment]
@lidel that seems like a more reasonable design :-)
Generally the add-ons that spam with pop-ups are the ones you *really* don't want to install lol.

**Comment by jessicaschilling** [comment]
@kallisti5 @lidel -- this sounds good to me. I'd still leave the toggle in the prefs though, just default to off ... some users may genuinely want the active reminder 😊

@lidel, I can stub this out once my IRL emergency dies down a bit, if you don't get to it first. Will probably still need a little help with the conditional on-first-load part though -- so either I can build the UX and you can wire it up, or you could drop in the code for some really barebones UI. LMK what you'd rather.

**Comment by lidel** [comment]
@jessicaschilling I can wire things up. no rush, I won't have bandwidth for this any time soon, so we can tackle this next+ week.

**Comment by jessicaschilling** [comment]
@lidel - https://github.com/ipfs-shipyard/ipfs-companion/pull/935 should be a useful start. Let me know if I can do anything else - thanks!

**Comment by kallisti5** [comment]
I can confirm 2.16.0 came out and the upgrade notification is a lot more reasonable.
I actually was still "pulled into" clicking it and looking at the release notes, but it didn't interrupt my workflow.

Nice work!
