### ISSUE TITLE
Can't add an IP address to "Always Disable IPFS Integrations" list.

### ISSUE THREAD

**Issue by Sierra410** [ipfs-shipyard/ipfs-companion#944]
I have 2 nodes one of which is hosted on a server I can access over VPN.
Attempting to access the remote gateway results in redirection to 127.0.0.1.
"Always Disable IPFS Integrations" list does not accept IP addresses - after clicking off the field the IP address disappears.

Tested in Firefox and Chromium, the behavior is identical.

**Comment by jessicaschilling** [comment]
Hey @Sierra410 - Thanks for identifying this use case. We'll prioritize as best we can but in full transparency the team is a bit slammed at the moment. Is this something you'd be interested in PRing?

**Comment by Sierra410** [comment]
I'll take a look, but since I'm unfamiliar with the codebase I might not be able to figure it out.

**Comment by Sierra410** [comment]
I think I got it

**Comment by jessicaschilling** [comment]
Sweet, thanks!

**Comment by Sierra410** [comment]
Why are you so mean, GitHub, why are you showing my mistakes to everyone /)c(\
