### ISSUE TITLE
IPFS Companion going on local gateway, but with wrong schema when in video

### ISSUE THREAD

**Issue by provirus** [ipfs-shipyard/ipfs-companion#954]
# Browser Setup

- OS: Linux Ubuntu 20.04.1 LTS
- Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- IPFS Companion Version: 2.16.0
- IPFS Companion has been reset to default preferences

# What is working (direct link to the video)

Steps:
- Going on https://www.foilen.com/handbrake-installer-sur-windows
- Clicking on "Téléchargez la vidéo" (below the video)
    - It requests https://cdn.foilen.com/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets https://tor.cdn.foilen.com/foilen/HandBrake - Installer sur Windows.mp4
    - It requests https://tor.cdn.foilen.com/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets http://localhost:8080/ipfs/QmdQUxS4Q4UEMWR3KCGv3PtcnAu8MJGSSwbhw6LuwwPgUv/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4
    - It requests http://localhost:8080/ipfs/QmdQUxS4Q4UEMWR3KCGv3PtcnAu8MJGSSwbhw6LuwwPgUv/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets http://bafybeig73kmxcne2tcuqgbzvzrgefjqynmvhocuuvan6bpm6n7dmeosu34.ipfs.localhost:8080/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4
    - [OK] It requests http://bafybeig73kmxcne2tcuqgbzvzrgefjqynmvhocuuvan6bpm6n7dmeosu34.ipfs.localhost:8080/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets the data

# What is not working (when in a video tag)

Steps:
- Going on https://www.foilen.com/handbrake-installer-sur-windows
- Clicking on the play button in the top-left corner of the video
    - It requests https://cdn.foilen.com/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets https://tor.cdn.foilen.com/foilen/HandBrake - Installer sur Windows.mp4
    - It requests https://tor.cdn.foilen.com/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4 and gets http://127.0.0.1:8080/ipfs/QmdQUxS4Q4UEMWR3KCGv3PtcnAu8MJGSSwbhw6LuwwPgUv/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4
    - [WRONG SCHEMA AND NOT GETING THE DATA] It requests https://127.0.0.1:8080/ipfs/QmdQUxS4Q4UEMWR3KCGv3PtcnAu8MJGSSwbhw6LuwwPgUv/foilen/HandBrake%20-%20Installer%20sur%20Windows.mp4

What is strange is that on the second call, it gets the right url to use, but on the third one, it decided to modify the url to HTTPS instead of keeping the HTTP.

thanks

**Comment by jessicaschilling** [comment]
@lidel Is this something you might be able to investigate when you're back? Thank you!

**Comment by provirus** [comment]
Hi,
thanks for testing it.

> If you want a quick fix as a Companion user, either toggle IPFS for this specific website via main menu

That is what I did in the meantime.

I reenabled it for fun and actually, it is now working correctly. I am checking the versions:

- Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)
- IPFS Companion Version: 2.17.1

So, both versions changed and now all is good. I must be lucky :)

> add DNSLink for fra.cdn.foilen.com (it is missing for fra subdomain, only cdn.foilen.com has valid one)

Actually, I didn't put one since all of them are all serving /ipns/cdn.foilen.com . There is no need for regional difference when on IPFS.

-----------

Thinking about it, maybe the fix is because now it can use the DNSLink for cdn.foilen.com instead of waiting for the X-Ipfs-Path since cdn.foilen.com is not returning any X-Ipfs-Path (the regional ones are returning X-Ipfs-Path) , but the url that it downloads is http://127.0.0.1:8080/ipns/cdn.foilen.com/foilen/HandBrake%20-%20Transcoder%20une%20video.mp4 (so the one with the cdn.foilen.com domain)
I am talking about the root cause of that other issue about resolving DNSLink: https://github.com/ipfs-shipyard/ipfs-companion/issues/953


thanks again

**Comment by lidel** [comment]
> > add DNSLink for fra.cdn.foilen.com (it is missing for fra subdomain, only cdn.foilen.com has valid one)
> 
> Actually, I didn't put one since all of them are all serving /ipns/cdn.foilen.com . There is no need for regional difference when on IPFS.

If you expose x-ipfs-path header, a DNSLink should also be there. It would not hurt :)
FYSA DNSLink-based redirects happen before header-based redirects, so this issue would probably not happen in the first place.

**Comment by provirus** [comment]
added it to my regional host names as well then. That could also be good if someone bookmarked the redirection.
Thanks for the suggestion :)
