### ISSUE TITLE
The "Provided by Brave" IPFS node option is not being offered

### ISSUE THREAD

**Issue by A2be** [ipfs-shipyard/ipfs-companion#958]
**Describe the bug**
The "Provided by Brave" IPFS node option is not being offered in the IPFS companion pull down as your doc says it should be.

**To Reproduce**
1. Go to Brave browser settings. Enable "IPFS Companion"
2. Both the companion webpage, and the recent issue at https://github.com/ipfs-shipyard/ipfs-companion/releases/tag/v2.17.0 say to select "Provided by Brave" as your IPFS node option in the companion.
3. No such option is offered.  I'm at a loss as to what to try next.

**Expected behavior**
A clear and explicit option in the pull down to do exactly what your IPFS doc is telling me to do.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Brave
 - Version Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)a

**Additional context**

**Comment by jessicaschilling** [comment]
@A2be Which version of Brave? IPFS support ships in Brave 1.19 (which isn't out quite yet), but you can give it a spin in the Nightly build until then: https://brave.com/download-nightly/

**Comment by lidel** [comment]
@A2be feel free to reopen if you can't see it in Brave >=1.19.x
