### ISSUE TITLE
Add multi-language support. 

### ISSUE THREAD

**Issue by FledgeXu** [ipfs-shipyard/ipfs-companion#963]
**Is your feature request related to a problem? Please describe.**
If ipfs-companion can have the multi-language support, it will more easily be introduced to none English native speakers.
**Describe the solution you'd like**
Add a language option and enable i18n.
**Describe alternatives you've considered**
Make some multi-language versions?

**Comment by jessicaschilling** [comment]
IPFS Companion already includes multi-language support, and should obey your browser/OS language. 

You can contribute translations, too:
https://www.transifex.com/ipfs/ipfs-companion/

Thanks - closing this issue.
