### ISSUE TITLE
Explore visual representation in menu when running Brave node

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-companion#965]
Right now we've got a pretty clear indicator when the user is running a js-ipfs node. Should we do something similar for when a user is running a Brave-internal node?

![image](https://user-images.githubusercontent.com/1507828/105059486-920c2200-5a34-11eb-888e-ce3109c116a4.png)

Suggestion: like this, but with a less pixellated lion. Could also explicitly note `0.7.0/Brave` or similar.
![image](https://user-images.githubusercontent.com/1507828/105067163-ac49fe00-5a3c-11eb-98d1-2f0bf0aa41f7.png)

**Comment by jessicaschilling** [comment]
@lidel your thoughts on this? Can get you a cube+lion SVG if you're game.

**Comment by lidel** [comment]
@jessicaschilling that will be perfect! 

ps. for some reason I would expect to lion to be on the left, but either way works! :thinking:

**Comment by jessicaschilling** [comment]
@lidel Sent you two SVGs under separate cover - let me know if you have any problems.
