### ISSUE TITLE
Chromium browser sync via IPFS

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-shipyard/ipfs-companion#973]
## Is your feature request related to a problem? Please describe.

Chromium is losing its ability to sync in March. See the link for a discussion about this:

https://lists.archlinux.org/pipermail/arch-dev-public/2021-January/030260.html

## Describe the solution you'd like
I was wondering if there's a chance to use IPFS to implement a serverless sync?

**Comment by lidel** [comment]
We are limited by Web Extension APIs available in Chromium.
Not sure if we could do anything more than History:

- https://developer.chrome.com/docs/extensions/reference/
  -  [`chrome.history` API](https://developer.chrome.com/docs/extensions/reference/history/) 

I'll ask our friends at Brave (iirc they built their own sync on top of Chromium), 
but I don't think one can implement sync without access to internal APIs.

**Comment by RubenKelevra** [comment]
Yeah my idea was to extend chromium to have an API where extentions could be granted permissions in the settings.

This would open a way to support sync within brave and within chromium itself without having to rely on a company's server.

**Comment by lidel** [comment]
FYSA Brave wrote their own Sync replacement which does not suffer from privacy issues present in Google Chrome:
- https://brave.com/sync-v2/
- https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-

Personally, I don't think we will see a public API for extensions that gives access to user's profile (passwords, settings), as the surface for abuse is too big. This needs to be built-in feature of the user agent itself, and without IPFS being part of Chromium network stack we can't even start this conversation. 

I'm closing this for now (can't do anything meaningful in Companion itself),
but we will be looking into leveraging IPFS/libp2p for storage/sync in user agents that introduce native IPFS over time.
