### ISSUE TITLE
Retain ipfs:// when localhost gateway is used

### ISSUE THREAD

**Issue by markg85** [ipfs-shipyard/ipfs-companion#974]
Hi,

I'm not quite sure if this is a bug or a feature. Or perhaps even well intentional but i don't understand it.

I'm running ipfs companion on the latest fancy brave (with IPFS):
Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) unknown (64-bit)

Now any IPFS site i visit gets this appended to the URL:
`ipns.localhost:8080`

I'm fine with that if i'm using http:// or https:// and that clearly shows i'm using a gateway. A local one in this case.
In this very specific case i'm visiting (as in typing in the url bar):
`ipns://dnslink.io`

Which gets rewritten to:
`http://dnslink.io.ipns.localhost:8080/`

This makes no sense to me.
I'm **specifically** using the `ipfs` protocol so i'm expecting it not to be rewritten to the http protocol.

Am i just missing a checkbox somewhere that would fix this?
Or is this a bug? Or an intentional feature?

Best regards,
Mark

**Comment by lidel** [comment]
Thank you for reporting this @markg85, this needs to be fixed in Brave.
Good news is that is already on the TODO list, we track it at https://github.com/brave/brave-browser/issues/13756

**Comment by markg85** [comment]
That is a better title indeed :) Thank you!

But i don't get why it's a Brave thing.
I'm also running chrome with ipfs companion and the exact same thing happens there.

I mean, somehow it does know how to resolve the site `ipns://dnslink.io` (ipfs companion magic i assume) but does redirect it to `http://dnslink.io.ipns.localhost:8080/`

**Comment by bbondy** [comment]
@markg85 can you explain how to reproduce?
For me if I have a gateway configured in settings it goes to: `https://dnslink-io.ipns.dweb.link/` which is expected.

Maybe a screenshot of your brave://settings/extensions please? Thanks!

**Comment by markg85** [comment]
> For me if I have a gateway configured in settings it goes to: `https://dnslink-io.ipns.dweb.link/` which is expected.

That is **exactly** the problem.
If i type in the urlbar **ipns://dnslink.io** and have a **local gateway** running then i expect the site to stay on that very site. The urlbar should stay at "ipns://dnslink.io" and not rewrite/redirect to the http link.

Btw. It's awesome that Brave now natively supports IPFS. Thank you for that, @bbondy!

**Comment by lidel** [comment]
Moved to: https://github.com/brave/brave-browser/issues/13872

**Comment by bbondy** [comment]
You might have this option on from brave://settings/extensions:
<img width="675" alt="Screen Shot 2021-02-03 at 3 38 39 PM" src="https://user-images.githubusercontent.com/831718/106806398-e8cd4a80-6635-11eb-818a-db7dd82a95f6.png">

**Comment by bbondy** [comment]
it'll retain the ipns:// URI with the issue that @lidel mentioned though, as long as the configured gateway is localhost and matching your setting.
