### ISSUE TITLE
Unable to connect to API of Brave node

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-companion#983]
Same issue in latest stable brave-browser-1.21.73-linux-amd64 & brave-browser-nightly-1.23.22-linux-amd64:

> ![2021-03-06--22-47-00](https://user-images.githubusercontent.com/157609/110221668-e4fb4500-7ecd-11eb-8ce5-715aa135c00f.png)

>  ![2021-03-06--22-37-37](https://user-images.githubusercontent.com/157609/110221675-ecbae980-7ecd-11eb-9192-b0a53c10e173.png)

> ![2021-03-06--22-38-15](https://user-images.githubusercontent.com/157609/110221652-bda47800-7ecd-11eb-9c42-e3ffa533360e.png)

**Comment by lidel** [comment]
Filled upstream issue https://github.com/brave/brave-browser/issues/14534, hopefully this was already fixed in https://github.com/brave/brave-core/pull/8158

**Comment by lidel** [comment]
Fixed in Brave v1.21.74

**Comment by OdysLam** [comment]
I am also experiencing a relevant issue. I can't use the IPFS webui using the IPFS node of brave. The error that I get is about CORS 
![image](https://user-images.githubusercontent.com/13405632/112766574-17a2e400-901b-11eb-8547-35cb2d52bf51.png)

**Comment by lidel** [comment]
@OdysLam what version of Brave are you running?

**Comment by OdysLam** [comment]
Hey @lidel , the latest: `Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64)`

**Comment by revmen** [comment]
Same problem here. Brave 1.24.86

IPFS Companion in Chrome can connect to the node that Brave is running, but the Brave plugin cannot.
